### ISSUE TITLE
Corrupted dn_spill forcing ASSERTION in zio.c:285

### ISSUE THREAD

**Issue by r0ssar00** [zfsonlinux/zfs#1912]
Timeline:
I (foolishly) started using zfs@HEAD on my media storage pool last week.  First thing I did after booting the new code was set xattr=sa on my media pool.

Netatalk caused a bug assertion so I opted to set xattr=off, then xattr=dir to attempt to get back the old xattr storage before a revert to zfs@0.6.2.

I then rebooted into zfs@0.6.2 only to discover that my media pool was no longer importing.  I queried dmesg and discovered it was bugging out.  I theorized it was due to the older code attempting to read the new format extended attributes so I unreverted back to zfs@HEAD so I could copy all the data off and recreate the pool.

As soon as I tried to import media, it would hit a bug in the same spot (hence, my theory was either misguided or correct, kernel code is absurdly hard to debug).

My next step was to boot up my emergency partition (my rootfs is on zfs as well, always handy to have an install around that doesn't use it) and run zdb on media to see what was going on.

I can consistently get zdb to crash with the same assertion (yay! This means I likely have the same problem as in kernel-land but this time can debug with gdb):
````
../../module/zfs/zio.c:285: zio_buf_alloc: Assertion `c < (1ULL << 17) >> 9' failed
````
End timeline.

At this point, I've been using gdb to comb through the structures and trying to figure out if there's a way to drop the offending dnode or blkptr from the disks but I'm at a loss.  What I *hope* to do is overwrite the dnode and/or blkptr in question using dd and exploit zfs' ability to report&ignore bad blocks so I can at least import and recover the data that's left.  Is this even possible?  I've read the on-disk layout document and am still at a loss.  

I'm not even sure if a situation like this should've even been possible based on the metadata consistency guarantees zfs makes.  I don't even know how the invalid data made it out to not only one vdev but *all* of them!

I've collected some information that may be of help:
pool structure:
````
media
        vdev_children: 4
        version: 5000
        pool_guid: 453305170067640071
        name: 'media'
        state: 0
        vdev_tree:
            type: 'root'
            id: 0
            guid: 453305170067640071
            children[0]:
                type: 'mirror'
                id: 0
                guid: 16130215666113252489
                whole_disk: 0
                metaslab_array: 39
                metaslab_shift: 34
                ashift: 12
                asize: 2000384688128
                is_log: 0
                create_txg: 4
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 9076908882072579750
                    whole_disk: 1
                    DTL: 54
                    create_txg: 4
                    path: '/dev/disk/by-id/ata-WDC_WD20EARS-00MVWB0_WD-WCAZA7579371-part1'
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 1606028819229543443
                    whole_disk: 1
                    DTL: 57
                    create_txg: 4
                    path: '/dev/disk/by-id/ata-SAMSUNG_HD204UI_S2HGJ1AZA04356-part1'
            children[1]:
                type: 'disk'
                id: 1
                guid: 9746420062916565190
                whole_disk: 1
                metaslab_array: 37
                metaslab_shift: 33
                ashift: 9
                asize: 1000189984768
                is_log: 0
                DTL: 53
                create_txg: 4
                path: '/dev/disk/by-id/ata-ST31000528AS_9VP5XQM3-part1'
            children[2]:
                type: 'mirror'
                id: 2
                guid: 11897324380956193185
                whole_disk: 0
                metaslab_array: 35
                metaslab_shift: 33
                ashift: 12
                asize: 1000189984768
                is_log: 0
                create_txg: 4
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 10433172601338277823
                    whole_disk: 1
                    DTL: 52
                    create_txg: 4
                    path: '/dev/disk/by-id/ata-ST1000DM003-9YN162_S1D1PG8D-part1'
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 5296172409562622271
                    whole_disk: 1
                    DTL: 55
                    create_txg: 4
                    path: '/dev/disk/by-id/ata-ST1000DM003-9YN162_S1D1QHGL-part1'
            children[3]:
                type: 'disk'
                id: 3
                guid: 2618541424481661114
                whole_disk: 0
                metaslab_array: 34
                metaslab_shift: 23
                ashift: 9
                asize: 1495793664
                is_log: 1
                DTL: 51
                create_txg: 4
                path: '/dev/disk/by-id/ata-MKNSSDCR60GB_MKN1303A0000161873-part2'
````
ZDB arguments:
-AAA -e -bsvLF 453305170067640071
Backtrace:
````
#0  0x00000039c8a359e9 in raise () from /lib64/libc.so.6
#1  0x00000039c8a370f8 in abort () from /lib64/libc.so.6
#2  0x00000039c8a2e956 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00000039c8a2ea02 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff79180af in zio_buf_alloc (size=14579200) at ../../module/zfs/zio.c:285
#5  0x00007ffff783d5eb in arc_get_data_buf (buf=0xaba3c20) at ../../module/zfs/arc.c:2666
#6  0x00007ffff7839aee in arc_buf_alloc (spa=0x624940, size=14579200, tag=0x0, type=ARC_BUFC_METADATA)
    at ../../module/zfs/arc.c:1417
#7  0x00007ffff783ed54 in arc_read (pio=0x0, spa=0x624940, bp=0x9ef8980, done=0x0, private=0x0, priority=6, 
    zio_flags=64, arc_flags=0x7fffffff384c, zb=0x7fffffff3880) at ../../module/zfs/arc.c:3149
#8  0x00007ffff7870e3f in traverse_prefetch_metadata (td=0x97c36f0, bp=0x9ef8980, zb=0x7fffffff3880)
    at ../../module/zfs/dmu_traverse.c:205
#9  0x00007ffff7871a6c in prefetch_dnode_metadata (td=0x97c36f0, dnp=0x9ef8800, objset=106, object=4)
    at ../../module/zfs/dmu_traverse.c:399
#10 0x00007ffff78714a8 in traverse_visitbp (td=0x97c36f0, dnp=0x9ef8000, bp=0x12b6000, zb=0x1100e520)
    at ../../module/zfs/dmu_traverse.c:309
#11 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x12b1000, zb=0x1100e720)
    at ../../module/zfs/dmu_traverse.c:286
#12 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x12ac000, zb=0x1100eaa0)
    at ../../module/zfs/dmu_traverse.c:286
#13 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x12a7000, zb=0x1142e520)
    at ../../module/zfs/dmu_traverse.c:286
#14 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x129f000, zb=0x1142e720)
    at ../../module/zfs/dmu_traverse.c:286
#15 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x129a000, zb=0x53c5190)
    at ../../module/zfs/dmu_traverse.c:286
#16 0x00007ffff787135b in traverse_visitbp (td=0x97c36f0, dnp=0x159d200, bp=0x159d240, zb=0x7fffffff3e90)
    at ../../module/zfs/dmu_traverse.c:286
#17 0x00007ffff7871b18 in traverse_dnode (td=0x97c36f0, dnp=0x159d200, objset=106, object=0)
    at ../../module/zfs/dmu_traverse.c:412
#18 0x00007ffff787168a in traverse_visitbp (td=0x97c36f0, dnp=0x0, bp=0x1590a80, zb=0x15977e0)
    at ../../module/zfs/dmu_traverse.c:344
#19 0x00007ffff78721ca in traverse_impl (spa=0x624940, ds=0x5407200, objset=106, rootbp=0x1590a80, 
    txg_start=20202, resume=0x0, flags=21, func=0x40b2c4 <zdb_blkptr_cb>, arg=0x7fffffff4220)
    at ../../module/zfs/dmu_traverse.c:550
#20 0x00007ffff78722fd in traverse_dataset (ds=0x5407200, txg_start=20202, flags=21, 
    func=0x40b2c4 <zdb_blkptr_cb>, arg=0x7fffffff4220) at ../../module/zfs/dmu_traverse.c:577
#21 0x00007ffff7872548 in traverse_pool (spa=0x624940, txg_start=0, flags=21, func=0x40b2c4 <zdb_blkptr_cb>, 
    arg=0x7fffffff4220) at ../../module/zfs/dmu_traverse.c:637
#22 0x000000000040be2e in dump_block_stats (spa=0x624940) at ../../cmd/zdb/zdb.c:2419
#23 0x000000000040ccd2 in dump_zpool (spa=0x624940) at ../../cmd/zdb/zdb.c:2727
#24 0x000000000040ec7d in main (argc=0, argv=0x7fffffffe500) at ../../cmd/zdb/zdb.c:3401
````
parent dnode_phys_t of offending dnode (printed while in frame 11):
````
$224 = {
  dn_type = 10 '\n', 
  dn_indblkshift = 14 '\016', 
  dn_nlevels = 7 '\a', 
  dn_nblkptr = 3 '\003', 
  dn_bonustype = 0 '\000', 
  dn_checksum = 0 '\000', 
  dn_compress = 0 '\000', 
  dn_flags = 1 '\001', 
  dn_datablkszsec = 32, 
  dn_bonuslen = 0, 
  dn_pad2 = "\000\000\000", 
  dn_maxblkid = 14208, 
  dn_used = 110437888, 
  dn_pad3 = {0, 0, 0, 0}, 
  dn_blkptr = {{
      blk_dva = {{
          dva_word = {8589934600, 1886882864}
        }, {
          dva_word = {8, 2524409928}
        }, {
          dva_word = {0, 0}
        }}, 
      blk_prop = 9658540060315811871, 
      blk_pad = {0, 0}, 
      blk_phys_birth = 0, 
      blk_birth = 803553, 
      blk_fill = 225281, 
      blk_cksum = {
        zc_word = {381058795444, 65810470948699, 6022366139653393, 386266145440635795}
      }
    }}, 
  dn_bonus = '\000' <repeats 191 times>, 
  dn_spill = {
    blk_dva = {{
        dva_word = {0, 0}
      }, {
        dva_word = {0, 0}
      }, {
        dva_word = {0, 0}
      }}, 
    blk_prop = 0, 
    blk_pad = {0, 0}, 
    blk_phys_birth = 0, 
    blk_birth = 0, 
    blk_fill = 0, 
    blk_cksum = {
      zc_word = {0, 0, 0, 0}
    }
  }
}
````
zdb_print_blkptr(bp, 0) (called in frame 10 and which I believe points to the dnode that contains the offending dnode in it's blkptr):
````
DVA[0]=<2:e0ef0cf000:1000> DVA[1]=<0:12ceed99000:1000> [L0 DMU dnode] fletcher4 lzjb LE contiguous unique double size=4000L/1000P birth=803549L/803549P fill=19 cksum=1007837d5d8:23d6f829a4384:30bcc263c0bf7fe:13b810e7e20fc95a
````
The offending dnode_phys_t is discovered while iterating through the metadata (dmu_traverse.c:308-3011) returned from that blkptr.  prefetch_dnode_metadata() for the dnp at index 4 is the call that ultimately leads to the assert.

The dnode that's causing me so much trouble:
````
$225 = {
  dn_type = 20 '\024', 
  dn_indblkshift = 14 '\016', 
  dn_nlevels = 2 '\002', 
  dn_nblkptr = 1 '\001', 
  dn_bonustype = 44 ',', 
  dn_checksum = 0 '\000', 
  dn_compress = 0 '\000', 
  dn_flags = 7 '\a', 
  dn_datablkszsec = 32, 
  dn_bonuslen = 272, 
  dn_pad2 = "\000\000\000", 
  dn_maxblkid = 32, 
  dn_used = 285184, 
  dn_pad3 = {0, 0, 0, 0}, 
  dn_blkptr = {{
      blk_dva = {{
          dva_word = {8589934600, 1886881232}
        }, {
          dva_word = {8, 2524408984}
        }, {
          dva_word = {0, 0}
        }}, 
      blk_prop = 9301066839893475359, 
      blk_pad = {0, 0}, 
      blk_phys_birth = 0, 
      blk_birth = 803549, 
      blk_fill = 33, 
      blk_cksum = {
        zc_word = {920954299313, 316996586558771, 65835010598884633, 10285276063045195251}
      }
    }}, 
  dn_bonus = "ZP/\000\004\b\030\000X\000\000\000\000\000\000\000\355A\000\000\000\000\000\000\r\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000\350\003\000\000\000\000\000\000\350\003\000\000\000\000\000\000\004\000\000\000\000\000\000\000D\001\000\000\b\004\000\000p&\221R\000\000\000\000~\205\351\064\000\000\000\000p&\221R\000\000\000\000~\205\351\064\000\000\000\000p&\221R\000\000\000\000~\205\351\064\000\000\000\000\203\353\214O\000\000\000\000`[\243\017\000\000\000\000\n\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\000\000\000\020\277\001\036\000\000\000@ \251\000\022\000\000\000\000@\251\000\022\000\a\000\000\000\000\000\000\000\001\001\000\000\000\000\000", 
  dn_spill = {
    blk_dva = {{
        dva_word = {4899916394595876864, 1152921505814806528}
      }, {
        dva_word = {8751735916204352883, 8679965255895708462}
      }, {
        dva_word = {2233785415343538176, 8457598907737930099}
      }}, 
    blk_prop = 6878231818129272634, 
    blk_pad = {7815259820786989682, 53271460077428}, 
    blk_phys_birth = 0, 
    blk_birth = 800819, 
    blk_fill = 1, 
    blk_cksum = {
      zc_word = {42198233579, 4566266076945, 250886316869651, 9328964013744530}
    }
  }
}
````
dn_flags indicate a spill is used but as you can see, the spill data is obviously quite wrong.

Also, even though it's highly specific to my system, a breakpoint at 
````
arc_read if zb->zb_blkid==18446744073709551614 && zb->zb_objset==106 && zb->zb_object==4 && zb->zb_level==0
````
will break just before the fatal call.

Is there any hope at all that I can get the pool to a point where I can recover what data is left?
