### ISSUE TITLE
zpool not able to use /dev/mapper devices directly

### ISSUE THREAD

**Issue by stevecs** [zfsonlinux/zfs#2276]
I have pools utilizing /dev/mapper devices.    Was able to create the pools using them directly with no issues.   However doing later operations (offline, replace) the device can't be found in the lookup.

```
zpool status
  pool: mpool0
 state: ONLINE
  scan: scrub repaired 212K in 15h10m with 0 errors on Tue Apr 22 07:38:04 2014
config:

        NAME         STATE     READ WRITE CKSUM
        mpool0       ONLINE       0     0     0
          raidz2-11  ONLINE       0     0     0
            c0t0d11  ONLINE       0     0     0
            c0t1d11  ONLINE       0     0     0
            c0t2d11  ONLINE       0     0     0
            c0t3d11  ONLINE       0     0     0
            c0t4d11  ONLINE       0     0     0
            c0t5d11  ONLINE       0     0     0
            c0t6d11  ONLINE       0     0     0


 zpool offline mpool0 c0t4d11
cannot offline c0t4d11: no such device in pool


zdb
mpool0:
    version: 5000
    name: 'mpool0'
    state: 0
    txg: 538953
    pool_guid: 1040814043491407337
    hostname: 'loki'
    vdev_children: 16
    vdev_tree:
        type: 'root'
        id: 0
        guid: 1040814043491407337
        children[0]:
            type: 'raidz'
            id: 0
            guid: 16698894809243682567
            nparity: 2
            metaslab_array: 48
            metaslab_shift: 37
            ashift: 12
            asize: 14002692816896
            is_log: 0
            create_txg: 4
        children[11]:
            type: 'raidz'
            id: 11
            guid: 6684601753102898458
            nparity: 2
            metaslab_array: 36
            metaslab_shift: 37
            ashift: 12
            asize: 14002692816896
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 16866663702709771763
                path: '/dev/mapper/c0t0d11-part1'
                whole_disk: 1
                DTL: 4205
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 1944983771268825856
                path: '/dev/mapper/c0t1d11-part1'
                whole_disk: 1
                DTL: 4204
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 14759553603506234383
                path: '/dev/mapper/c0t2d11-part1'
                whole_disk: 1
                DTL: 4203
                create_txg: 4
            children[3]:
                type: 'disk'
                id: 3
                guid: 12721306347944131798
                path: '/dev/mapper/c0t3d11-part1'
                whole_disk: 1
                DTL: 4202
                create_txg: 4
            children[4]:
                type: 'disk'
                id: 4
                guid: 2079194606608502994
                path: '/dev/mapper/c0t4d11-part1'
                whole_disk: 1
                DTL: 4201
                create_txg: 4
            children[5]:
                type: 'disk'
                id: 5
                guid: 3691722712802273264
                path: '/dev/mapper/c0t5d11-part1'
                whole_disk: 1
                DTL: 4200
                create_txg: 4
            children[6]:
                type: 'disk'
                id: 6
                guid: 14465804083040849724
                path: '/dev/mapper/c0t6d11-part1'
                whole_disk: 1
                DTL: 4199
                create_txg: 4
```

I have to use the guid to offline the device:

```
zpool offline mpool0 2079194606608502994
```

```
zpool replace -f mpool0 -o ashift=12 /dev/mapper/c0t4d11 /dev/mapper/c0t4d11
cannot replace /dev/mapper/c0t4d11 with /dev/mapper/c0t4d11: no such device in pool

 zpool replace -f mpool0 -o ashift=12 2079194606608502994  /dev/mapper/c0t4d11
```
