### ISSUE TITLE
zfs status -d units not clear

### ISSUE THREAD

**Issue by ioquatix** [zfsonlinux/zfs#2414]
The units are not clear

```
# zpool status -D
  pool: backup
 state: ONLINE
  scan: none requested
config:

        NAME                                        STATE     READ WRITE CKSUM
        backup                                      ONLINE       0     0     0
          ata-eSATA-2_ExternalRAID_WD-WCAZA6489285  ONLINE       0     0     0

errors: No known data errors

 dedup: DDT entries 3255693, size 311 on disk, 179 in core
```

311 whats? 179 whats?
