### ISSUE TITLE
async destroy stops freeing at 8K

### ISSUE THREAD

**Issue by fling-** [zfsonlinux/zfs#2428]
```
vds2 ~ # zpool get freeing   
NAME  PROPERTY  VALUE    SOURCE
vds2  freeing   8K       default
```

```
vds2 ~ # cat /sys/module/zfs/version
0.6.2-282_g6795a69
vds2 ~ # zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
vds2  2,66T   612G  2,06T    22%  1.81x  ONLINE  -
vds2 ~ # zdb
vds2:  
    version: 5000
    name: 'vds2'
    state: 0
    txg: 1996540
    pool_guid: 8050736527622700973
    errata: 0
    hostid: 3742314149
    hostname: 'vds2'  
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 8050736527622700973
        children[0]:
            type: 'mirror'  
            id: 0
            guid: 3197540399751031490
            whole_disk: 0
            metaslab_array: 34
            metaslab_shift: 34
            ashift: 12
            asize: 2930201853952
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 5115699992981706208  
                path: '/dev/sdb3'
                whole_disk: 0
                DTL: 49  
                create_txg: 4
            children[1]:
                type: 'disk'  
                id: 1
                guid: 4733021831987595720
                path: '/dev/sda3'
                whole_disk: 0
                DTL: 47  
                create_txg: 4
    features_for_read:
```
