### ISSUE TITLE
Pool is stuck waiting for the transaction group to sync

### ISSUE THREAD

**Issue by ajeffco** [zfsonlinux/zfs#2871]
After running a scrub against both pools on the server, one of the pools appears to be hung.  I tried to cancel with "zpool scrub -s vault" and it hung.  All commands against the pool appear to be hanging, as are most processes using the pool.

```
root@core:~# zdb
media:
    version: 5000
    name: 'media'
    state: 0
    txg: 1949488
    pool_guid: 11410556170326843899
    errata: 0
    hostid: 168428554
    hostname: 'core'
    vdev_children: 3
    vdev_tree:
        type: 'root'
        id: 0
        guid: 11410556170326843899
        children[0]:
            type: 'raidz'
            id: 0
            guid: 15956916485752976401
            nparity: 1
            metaslab_array: 37
            metaslab_shift: 35
            ashift: 12
            asize: 6001154064384
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 4404432886433789862
                path: '/dev/disk/by-id/ata-ST32000644NS_59Y5484_59Y1810IBM_9WM0JX50-part1'
                whole_disk: 1
                DTL: 451
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 969564804822139897
                path: '/dev/disk/by-id/ata-HUA723020ALA640_59Y5484_59Y1810IBM_YFGLYT8A-part1'
                whole_disk: 1
                DTL: 450
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 9445938006208192842
                path: '/dev/disk/by-id/ata-ST32000644NS_59Y5484_59Y1810IBM_9WM0S42S-part1'
                whole_disk: 1
                DTL: 449
                create_txg: 4
        children[1]:
            type: 'raidz'
            id: 1
            guid: 10096331820383410267
            nparity: 1
            metaslab_array: 34
            metaslab_shift: 35
            ashift: 12
            asize: 6001154064384
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 13506755040365369216
                path: '/dev/disk/by-id/ata-ST32000644NS_59Y5484_59Y1810IBM_9WM0JXY4-part1'
                whole_disk: 1
                DTL: 457
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 5626454168492155625
                path: '/dev/disk/by-id/ata-HUA722020ALA330_59Y5484_59Y1807IBM_JK11B1BFGG1TSF-part1'
                whole_disk: 1
                DTL: 456
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 912776479545881143
                path: '/dev/disk/by-id/ata-HUA722020ALA330_59Y5484_59Y1807IBM_JK11B1BFGDV2LR-part1'
                whole_disk: 1
                DTL: 455
                create_txg: 4
        children[2]:
            type: 'raidz'
            id: 2
            guid: 5226440511684987825
            nparity: 1
            metaslab_array: 377
            metaslab_shift: 35
            ashift: 9
            asize: 6001154064384
            is_log: 0
            create_txg: 26061
            children[0]:
                type: 'disk'
                id: 0
                guid: 10624024194481459955
                path: '/dev/disk/by-id/ata-HUA723020ALA640_59Y5484_59Y1810IBM_YFJP8KMA-part1'
                whole_disk: 1
                DTL: 454
                create_txg: 26061
            children[1]:
                type: 'disk'
                id: 1
                guid: 2765193101110132189
                path: '/dev/disk/by-id/ata-Hitachi_HDS5C3020ALA632_ML0220F30XN4DD-part1'
                whole_disk: 1
                DTL: 453
                create_txg: 26061
            children[2]:
                type: 'disk'
                id: 2
                guid: 2227868683201940255
                path: '/dev/disk/by-id/ata-HUA722020ALA330_59Y5484_59Y1807IBM_JK11B1BFH7SP4F-part1'
                whole_disk: 1
                DTL: 452
                create_txg: 26061
    features_for_read:
vault:
    version: 5000
    name: 'vault'
    state: 0
    txg: 15
    pool_guid: 14511596176310977096
    errata: 0
    hostid: 168428554
    hostname: 'core'
    vdev_children: 3
    vdev_tree:
        type: 'root'
        id: 0
        guid: 14511596176310977096
        children[0]:
            type: 'mirror'
            id: 0
            guid: 17059595635711463748
            metaslab_array: 38
            metaslab_shift: 31
            ashift: 12
            asize: 299985534976
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 10950308828392885094
                path: '/dev/disk/by-id/scsi-35000c5004841fb53-part1'
                whole_disk: 1
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 6270527447460244436
                path: '/dev/disk/by-id/scsi-35000c5004b8c8307-part1'
                whole_disk: 1
                create_txg: 4
        children[1]:
            type: 'mirror'
            id: 1
            guid: 9523813427366097755
            metaslab_array: 36
            metaslab_shift: 31
            ashift: 12
            asize: 299985534976
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 3803510417922049838
                path: '/dev/disk/by-id/scsi-35000c50047c33d7f-part1'
                whole_disk: 1
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 15807689885816629581
                path: '/dev/disk/by-id/scsi-35000c5004b8c1da7-part1'
                whole_disk: 1
                create_txg: 4
        children[2]:
            type: 'mirror'
            id: 2
            guid: 11368729946180450051
            metaslab_array: 34
            metaslab_shift: 30
            ashift: 12
            asize: 146800115712
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 14648308262357891975
                path: '/dev/disk/by-id/scsi-35000c5002c0125cb-part1'
                whole_disk: 1
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 10516575887676337662
                path: '/dev/disk/by-id/scsi-3500000e115d881a0-part1'
                whole_disk: 1
                create_txg: 4
    features_for_read:
```

Hardware info:
8 core AMD rig with 32GB non-ecc ram, it is not virtualized.

Linux Distribution:
Ubuntu 14.04.1 LTS

root@core:~# uname -a
Linux core 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Using the ZoL package
root@core:~#  dmesg | grep -E 'SPL:|ZFS:'
[   13.197075] SPL: Loaded module v0.6.3-1~trusty
[   13.229432] ZFS: Loaded module v0.6.3-2~trusty, ZFS pool version 5000, ZFS filesystem version 5

```
root@core:~# for param in /sys/module/{spl,zfs}/parameters/*; do printf "%-50s" `basename $param`; cat $param; done
spl_debug_mask                                    188
spl_debug_mb                                      -1
spl_debug_panic_on_bug                            0
spl_debug_printk                                  60
spl_debug_subsys                                  18446744073709551615
spl_hostid                                        168428554
spl_hostid_path                                   /etc/hostid
spl_kmem_cache_expire                             2
spl_kmem_cache_kmem_limit                         1024
spl_kmem_cache_max_size                           32
spl_kmem_cache_obj_per_slab                       16
spl_kmem_cache_obj_per_slab_min                   8
spl_kmem_cache_reclaim                            1
spl_kmem_cache_slab_limit                         0
spl_taskq_thread_bind                             0
l2arc_feed_again                                  1
l2arc_feed_min_ms                                 200
l2arc_feed_secs                                   1
l2arc_headroom                                    2
l2arc_headroom_boost                              200
l2arc_nocompress                                  0
l2arc_noprefetch                                  1
l2arc_norw                                        0
l2arc_write_boost                                 8388608
l2arc_write_max                                   8388608
metaslab_debug_load                               0
metaslab_debug_unload                             0
spa_asize_inflation                               24
spa_config_path                                   /etc/zfs/zpool.cache
zfetch_array_rd_sz                                1048576
zfetch_block_cap                                  256
zfetch_max_streams                                8
zfetch_min_sec_reap                               2
zfs_arc_grow_retry                                5
zfs_arc_max                                       17179869184
zfs_arc_memory_throttle_disable                   1
zfs_arc_meta_limit                                10737418240
zfs_arc_meta_prune                                1048576
zfs_arc_min                                       0
zfs_arc_min_prefetch_lifespan                     250
zfs_arc_p_aggressive_disable                      1
zfs_arc_p_dampener_disable                        1
zfs_arc_shrink_shift                              5
zfs_autoimport_disable                            0
zfs_dbuf_state_index                              0
zfs_deadman_enabled                               1
zfs_deadman_synctime_ms                           1000000
zfs_dedup_prefetch                                1
zfs_delay_min_dirty_percent                       60
zfs_delay_scale                                   500000
zfs_dirty_data_max                                3369619865
zfs_dirty_data_max_max                            8424049664
zfs_dirty_data_max_max_percent                    25
zfs_dirty_data_max_percent                        10
zfs_dirty_data_sync                               67108864
zfs_disable_dup_eviction                          0
zfs_expire_snapshot                               300
zfs_flags                                         1
zfs_free_min_time_ms                              1000
zfs_immediate_write_sz                            32768
zfs_mdcomp_disable                                0
zfs_nocacheflush                                  0
zfs_nopwrite_enabled                              1
zfs_no_scrub_io                                   0
zfs_no_scrub_prefetch                             0
zfs_pd_blks_max                                   100
zfs_prefetch_disable                              0
zfs_read_chunk_size                               1048576
zfs_read_history                                  0
zfs_read_history_hits                             0
zfs_recover                                       0
zfs_resilver_delay                                2
zfs_resilver_min_time_ms                          3000
zfs_scan_idle                                     50
zfs_scan_min_time_ms                              1000
zfs_scrub_delay                                   4
zfs_send_corrupt_data                             0
zfs_sync_pass_deferred_free                       2
zfs_sync_pass_dont_compress                       5
zfs_sync_pass_rewrite                             2
zfs_top_maxinflight                               32
zfs_txg_history                                   0
zfs_txg_timeout                                   5
zfs_vdev_aggregation_limit                        131072
zfs_vdev_async_read_max_active                    3
zfs_vdev_async_read_min_active                    1
zfs_vdev_async_write_active_max_dirty_percent     60
zfs_vdev_async_write_active_min_dirty_percent     30
zfs_vdev_async_write_max_active                   10
zfs_vdev_async_write_min_active                   1
zfs_vdev_cache_bshift                             16
zfs_vdev_cache_max                                16384
zfs_vdev_cache_size                               0
zfs_vdev_max_active                               1000
zfs_vdev_mirror_switch_us                         10000
zfs_vdev_read_gap_limit                           32768
zfs_vdev_scheduler                                noop
zfs_vdev_scrub_max_active                         2
zfs_vdev_scrub_min_active                         1
zfs_vdev_sync_read_max_active                     10
zfs_vdev_sync_read_min_active                     10
zfs_vdev_sync_write_max_active                    10
zfs_vdev_sync_write_min_active                    10
zfs_vdev_write_gap_limit                          4096
zfs_zevent_cols                                   80
zfs_zevent_console                                0
zfs_zevent_len_max                                128
zil_replay_disable                                0
zil_slog_limit                                    1048576
zio_bulk_flags                                    0
zio_delay_max                                     30000
zio_injection_enabled                             0
zio_requeue_io_start_cut_in_line                  1
zvol_inhibit_dev                                  0
zvol_major                                        230
zvol_max_discard_blocks                           16384
zvol_threads                                      32
```

The server is a mysql server and a file server for NFS and SMB.

```
root@core:~# cat /tmp/stacktraces.log
839:

[<ffffffffa01e5485>] cv_wait_common+0x105/0x1a0 [spl]
[<ffffffffa01e5535>] __cv_wait+0x15/0x20 [spl]
[<ffffffffa02b685b>] dsl_scan_sync+0x81b/0xb30 [zfs]
[<ffffffffa02c6fc2>] spa_sync+0x482/0xb00 [zfs]
[<ffffffffa02d783e>] txg_sync_thread+0x37e/0x5c0 [zfs]
[<ffffffffa01dda8a>] thread_generic_wrapper+0x7a/0x90 [spl]
[<ffffffff8108b492>] kthread+0xd2/0xf0
[<ffffffff8172f73c>] ret_from_fork+0x7c/0xb0
[<ffffffffffffffff>] 0xffffffffffffffff
===
21335:
zpoolscrub-svault
[<ffffffffa01e5485>] cv_wait_common+0x105/0x1a0 [spl]
[<ffffffffa01e5535>] __cv_wait+0x15/0x20 [spl]
[<ffffffffa02d6843>] txg_wait_synced+0xb3/0x190 [zfs]
[<ffffffffa02b6e23>] dsl_sync_task+0xf3/0x260 [zfs]
[<ffffffffa02b536f>] dsl_scan_cancel+0x2f/0x40 [zfs]
[<ffffffffa02c668c>] spa_scan_stop+0x3c/0x50 [zfs]
[<ffffffffa02fa63d>] zfs_ioc_pool_scan+0x5d/0x70 [zfs]
[<ffffffffa02fc2c6>] zfsdev_ioctl+0x466/0x4e0 [zfs]
[<ffffffff811d03c0>] do_vfs_ioctl+0x2e0/0x4c0
[<ffffffff811d0621>] SyS_ioctl+0x81/0xa0
[<ffffffff8172f7ed>] system_call_fastpath+0x1a/0x1f
[<ffffffffffffffff>] 0xffffffffffffffff
===
```

```
root@core:~# cat /proc/spl/kstat/zfs/arcstats
5 1 0x01 85 4080 13078796987 90196952226154
name                            type data
hits                            4    18429368
misses                          4    35983876
demand_data_hits                4    13
demand_data_misses              4    29448233
demand_metadata_hits            4    16638324
demand_metadata_misses          4    405721
prefetch_data_hits              4    0
prefetch_data_misses            4    13
prefetch_metadata_hits          4    1791031
prefetch_metadata_misses        4    6129909
mru_hits                        4    5557721
mru_ghost_hits                  4    4258097
mfu_hits                        4    11880293
mfu_ghost_hits                  4    25054348
deleted                         4    6117096
recycle_miss                    4    5381012
mutex_miss                      4    5260
evict_skip                      4    332352322
evict_l2_cached                 4    0
evict_l2_eligible               4    4549284352
evict_l2_ineligible             4    87367629312
hash_elements                   4    1680847
hash_elements_max               4    1686088
hash_collisions                 4    10186572
hash_chains                     4    435413
hash_chain_max                  4    17
p                               4    0
c                               4    17179869184
c_min                           4    4194304
c_max                           4    17179869184
size                            4    11870110864
hdr_size                        4    575860992
data_size                       4    1175274496
meta_size                       4    10049325056
other_size                      4    69650320
anon_size                       4    1175872512
anon_evict_data                 4    0
anon_evict_metadata             4    0
mru_size                        4    32870912
mru_evict_data                  4    512
mru_evict_metadata              4    6856704
mru_ghost_size                  4    17146390016
mru_ghost_evict_data            4    13789580288
mru_ghost_evict_metadata        4    3356809728
mfu_size                        4    10015856128
mfu_evict_data                  4    0
mfu_evict_metadata              4    10002537984
mfu_ghost_size                  4    31369216
mfu_ghost_evict_data            4    1458176
mfu_ghost_evict_metadata        4    29911040
l2_hits                         4    0
l2_misses                       4    0
l2_feeds                        4    0
l2_rw_clash                     4    0
l2_read_bytes                   4    0
l2_write_bytes                  4    0
l2_writes_sent                  4    0
l2_writes_done                  4    0
l2_writes_error                 4    0
l2_writes_hdr_miss              4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    0
l2_io_error                     4    0
l2_size                         4    0
l2_asize                        4    0
l2_hdr_size                     4    0
l2_compress_successes           4    0
l2_compress_zeros               4    0
l2_compress_failures            4    0
memory_throttle_count           4    0
duplicate_buffers               4    0
duplicate_buffers_size          4    0
duplicate_reads                 4    0
memory_direct_count             4    0
memory_indirect_count           4    0
arc_no_grow                     4    0
arc_tempreserve                 4    0
arc_loaned_bytes                4    0
arc_prune                       4    657855
arc_meta_used                   4    10694836368
arc_meta_limit                  4    10737418240
arc_meta_max                    4    10744528848
```

```
root@core:~# cat /proc/spl/kmem/slab
--------------------- cache -------------------------------------------------------  ----- slab ------  ---- object -----  --- emergency ---
name                                    flags      size     alloc slabsize  objsize  total alloc   max  total alloc   max  dlock alloc   max
spl_vn_cache                          0x00020         0         0     4096       96      0     0     1      0     0    21      0     0     0
spl_vn_file_cache                     0x00020         0         0     4096      104      0     0     0      0     0     0      0     0     0
spl_zlib_workspace_cache              0x00240         0         0  8388608   268104      0     0     0      0     0     0      0     0     0
space_seg_cache                       0x00020   6995968   3348608     4096       64   1708  1707  1707  64904 52322 64866      0     0     0
ddt_cache                             0x00040    524288    496960   524288    24848      1     1     1     21    20    21      0     0     0
ddt_entry_cache                       0x00020         0         0     8192      448      0     0     0      0     0     0      0     0     0
zio_cache                             0x00040  12058624    504360    32768     1080    368    24   546  10672   467 15834      0     0     0
zio_link_cache                        0x00020   1019904     50304     4096       48    249    40   357  11205  1048 16065      0     0     0
zio_vdev_cache                        0x00040 121634816 105525840  4194304   131088     29    29    40    870   805  1194      0     0     0
zio_buf_512                           0x00020  38502400  15422464    32768      512   1175  1061  1174  36425 30122 36394      0     0     0
zio_data_buf_512                      0x00020   1376256    519680    32768      512     42    41    59   1302  1015  1829      0     0     0
zio_buf_1024                          0x00040   1638400    726016    32768     1024     50    44   101   1050   709  2121      0     0     0
zio_data_buf_1024                     0x00040     98304     43008    32768     1024      3     2    43     63    42   903      0     0     0
zio_buf_1536                          0x00040   1703936    895488    65536     1536     26    24    29    806   583   899      0     0     0
zio_data_buf_1536                     0x00040    262144    142848    65536     1536      4     3    30    124    93   930      0     0     0
zio_buf_2048                          0x00040   2162688    983040    65536     2048     33    27    32    825   480   800      0     0     0
zio_data_buf_2048                     0x00040     65536      6144    65536     2048      1     1    33     25     3   825      0     0     0
zio_buf_2560                          0x00040   2228224   1282560    65536     2560     34    30    37    714   501   777      0     0     0
zio_data_buf_2560                     0x00040         0         0    65536     2560      0     0    41      0     0   861      0     0     0
zio_buf_3072                          0x00040   2621440   1566720    65536     3072     40    36    43    720   510   774      0     0     0
zio_data_buf_3072                     0x00040    327680    221184    65536     3072      5     4    45     90    72   810      0     0     0
zio_buf_3584                          0x00040   3014656   1756160   131072     3584     23    20    24    713   490   744      0     0     0
zio_data_buf_3584                     0x00040    393216    222208   131072     3584      3     2    29     93    62   899      0     0     0
zio_buf_4096                          0x00040  12320768   2433024   262144     4096     47    26    64   1457   594  1984      0     0     0
zio_data_buf_4096                     0x00040    524288    126976   262144     4096      2     1    15     62    31   465      0     0     0
zio_buf_5120                          0x00040   4849664   1413120   131072     5120     37    18    36    777   276   756      0     0     0
zio_data_buf_5120                     0x00040    131072      5120   131072     5120      1     1    23     21     1   483      0     0     0
zio_buf_6144                          0x00040   4587520   1794048   131072     6144     35    20    41    630   292   738      0     0     0
zio_data_buf_6144                     0x00040    131072      6144   131072     6144      1     1    26     18     1   468      0     0     0
zio_buf_7168                          0x00040   3145728   1756160   262144     7168     12    11    14    372   245   434      0     0     0
zio_data_buf_7168                     0x00040    524288    243712   262144     7168      2     2    16     62    34   496      0     0     0
zio_buf_8192                          0x00040  19660800   1982464   262144     8192     75    15   160   1575   242  3360      0     0     0
zio_data_buf_8192                     0x00040    524288    172032   262144     8192      2     1    25     42    21   525      0     0     0
zio_buf_10240                         0x00040   4718592   2344960   262144    10240     18    14    21    378   229   441      0     0     0
zio_data_buf_10240                    0x00040   2097152   1505280   262144    10240      8     7    25    168   147   525      0     0     0
zio_buf_12288                         0x00040  24117248   2592768   524288    12288     46    11    45   1426   211  1395      0     0     0
zio_data_buf_12288                    0x00040   1048576    380928   524288    12288      2     1    17     62    31   527      0     0     0
zio_buf_14336                         0x00040   6291456   3182592   524288    14336     12    11    16    372   222   496      0     0     0
zio_data_buf_14336                    0x00040   1048576    444416   524288    14336      2     1    17     62    31   527      0     0     0
zio_buf_16384                         0x00040 12948865024 10050043904   524288    16384  24698 24697 25372  617450 613406 634300      0     0     0
zio_data_buf_16384                    0x00040 1590165504 1175322624   524288    16384   3033  3002  4248  75825 71736 106200      0     0     0
zio_buf_20480                         0x00040   1048576    430080   524288    20480      2     1     3     42    21    63      0     0     0
zio_data_buf_20480                    0x00040         0         0   524288    20480      0     0     0      0     0     0      0     0     0
zio_buf_24576                         0x00040         0         0   524288    24576      0     0    62      0     0  1116      0     0     0
zio_data_buf_24576                    0x00040         0         0   524288    24576      0     0    18      0     0   324      0     0     0
zio_buf_28672                         0x00040   2097152    888832  1048576    28672      2     1     3     62    31    93      0     0     0
zio_data_buf_28672                    0x00040         0         0  1048576    28672      0     0     2      0     0    62      0     0     0
zio_buf_32768                         0x00040         0         0  1048576    32768      0     0     1      0     0    28      0     0     0
zio_data_buf_32768                    0x00040         0         0  1048576    32768      0     0     1      0     0    28      0     0     0
zio_buf_36864                         0x00040  13631488   3022848  1048576    36864     13    13    17    325    82   425      0     0     0
zio_data_buf_36864                    0x00040         0         0  1048576    36864      0     0     1      0     0    25      0     0     0
zio_buf_40960                         0x00040   2097152    942080  1048576    40960      2     1     5     46    23   115      0     0     0
zio_data_buf_40960                    0x00040         0         0  1048576    40960      0     0     3      0     0    69      0     0     0
zio_buf_45056                         0x00040         0         0  1048576    45056      0     0     3      0     0    63      0     0     0
zio_data_buf_45056                    0x00040         0         0  1048576    45056      0     0     2      0     0    42      0     0     0
zio_buf_49152                         0x00040         0         0  1048576    49152      0     0     0      0     0     0      0     0     0
zio_data_buf_49152                    0x00040         0         0  1048576    49152      0     0     0      0     0     0      0     0     0
zio_buf_53248                         0x00040         0         0  1048576    53248      0     0     0      0     0     0      0     0     0
zio_data_buf_53248                    0x00040         0         0  1048576    53248      0     0     0      0     0     0      0     0     0
zio_buf_57344                         0x00040         0         0  1048576    57344      0     0     0      0     0     0      0     0     0
zio_data_buf_57344                    0x00040         0         0  1048576    57344      0     0     0      0     0     0      0     0     0
zio_buf_61440                         0x00040         0         0  2097152    61440      0     0     0      0     0     0      0     0     0
zio_data_buf_61440                    0x00040         0         0  2097152    61440      0     0     0      0     0     0      0     0     0
zio_buf_65536                         0x00040         0         0  2097152    65536      0     0     5      0     0   150      0     0     0
zio_data_buf_65536                    0x00040         0         0  2097152    65536      0     0     0      0     0     0      0     0     0
zio_buf_69632                         0x00040         0         0  2097152    69632      0     0     0      0     0     0      0     0     0
zio_data_buf_69632                    0x00040         0         0  2097152    69632      0     0     0      0     0     0      0     0     0
zio_buf_73728                         0x00040         0         0  2097152    73728      0     0     0      0     0     0      0     0     0
zio_data_buf_73728                    0x00040         0         0  2097152    73728      0     0     0      0     0     0      0     0     0
zio_buf_77824                         0x00040         0         0  2097152    77824      0     0     0      0     0     0      0     0     0
zio_data_buf_77824                    0x00040         0         0  2097152    77824      0     0     0      0     0     0      0     0     0
zio_buf_81920                         0x00040         0         0  2097152    81920      0     0     0      0     0     0      0     0     0
zio_data_buf_81920                    0x00040         0         0  2097152    81920      0     0     0      0     0     0      0     0     0
zio_buf_86016                         0x00040         0         0  2097152    86016      0     0     0      0     0     0      0     0     0
zio_data_buf_86016                    0x00040         0         0  2097152    86016      0     0     0      0     0     0      0     0     0
zio_buf_90112                         0x00040         0         0  2097152    90112      0     0     0      0     0     0      0     0     0
zio_data_buf_90112                    0x00040         0         0  2097152    90112      0     0     0      0     0     0      0     0     0
zio_buf_94208                         0x00040         0         0  2097152    94208      0     0     0      0     0     0      0     0     0
zio_data_buf_94208                    0x00040         0         0  2097152    94208      0     0     0      0     0     0      0     0     0
zio_buf_98304                         0x00040         0         0  2097152    98304      0     0     0      0     0     0      0     0     0
zio_data_buf_98304                    0x00040         0         0  2097152    98304      0     0     0      0     0     0      0     0     0
zio_buf_102400                        0x00040         0         0  2097152   102400      0     0     0      0     0     0      0     0     0
zio_data_buf_102400                   0x00040         0         0  2097152   102400      0     0     0      0     0     0      0     0     0
zio_buf_106496                        0x00040         0         0  2097152   106496      0     0     0      0     0     0      0     0     0
zio_data_buf_106496                   0x00040         0         0  2097152   106496      0     0     0      0     0     0      0     0     0
zio_buf_110592                        0x00040         0         0  2097152   110592      0     0     0      0     0     0      0     0     0
zio_data_buf_110592                   0x00040         0         0  2097152   110592      0     0     0      0     0     0      0     0     0
zio_buf_114688                        0x00040         0         0  2097152   114688      0     0     8      0     0   136      0     0     0
zio_data_buf_114688                   0x00040         0         0  2097152   114688      0     0     0      0     0     0      0     0     0
zio_buf_118784                        0x00040         0         0  2097152   118784      0     0     0      0     0     0      0     0     0
zio_data_buf_118784                   0x00040         0         0  2097152   118784      0     0     0      0     0     0      0     0     0
zio_buf_122880                        0x00040         0         0  2097152   122880      0     0     0      0     0     0      0     0     0
zio_data_buf_122880                   0x00040         0         0  2097152   122880      0     0     0      0     0     0      0     0     0
zio_buf_126976                        0x00040         0         0  4194304   126976      0     0     0      0     0     0      0     0     0
zio_data_buf_126976                   0x00040         0         0  4194304   126976      0     0     0      0     0     0      0     0     0
zio_buf_131072                        0x00040  16777216   1441792  4194304   131072      4     4    34    124    11  1031      0     0     0
zio_data_buf_131072                   0x00040         0         0  4194304   131072      0     0     0      0     0     0      0     0     0
lz4_cache                             0x00040   4718592   4063232   524288    16384      9     8     8    279   248   248      0     0     0
sa_cache                              0x00020   4489216   2536600     4096       88   1096   954  1095  33976 28825 33945      0     0     0
spill_cache                           0x00040         0         0  4194304   131072      0     0     0      0     0     0      0     0     0
dnode_t                               0x00020  38076416  30387840    16384      952   2324  2076  2323  37184 31920 37168      0     0     0
dmu_buf_impl_t                        0x00020  41230336  31352832     8192      288   5033  4940  5755  120792 108864 138120      0     0     0
arc_buf_hdr_t                         0x00020 600088576 518980352     8192      296  73253 73219 74157  1758072 1753312 1779768      0     0     0
arc_buf_t                             0x00020  86065152  55028720     4096       80  21012 20989 21864  693396 687859 721512      0     0     0
l2arc_buf_hdr_t                       0x00020         0         0     4096       40      0     0     0      0     0     0      0     0     0
zil_lwb_cache                         0x00020 292655104 228625000     4096      200  71449 71449 71449  1143184 1143125 1143184      0     0     0
zfs_znode_cache                       0x00020  37027840  29434080    32768     1040   1130   970  1129  33900 28302 33870      0     0     0
```
