### ISSUE TITLE
zdb shows resilvering but zpool does not

### ISSUE THREAD

**Issue by andynormancx** [zfsonlinux/zfs#2973]
On my Ubuntu 12.04 ZoL 0.6.2 machine, zdb shows resilvering on one of my drives but zpool does not.

My setup is slightly out of the ordinary, I value redundancy over capacity or performance so I have a three drive mirror. As far as I can see everything is working well, but for some reason zdb thinks one of drives is resilvering.

When this array was first built there was a problem drive as one of the three in the mirror, it kept dropping off the SATA connection. The drive showing as resilvering in zdb is the one that replaced the faulty drive.

```
  pool: nexus
 state: ONLINE
  scan: scrub repaired 0 in 2h54m with 0 errors on Thu Dec 18 10:56:11 2014
config:

    NAME                                                 STATE     READ WRITE CKSUM
    nexus                                                ONLINE       0     0     0
      mirror-0                                           ONLINE       0     0     0
        scsi-SATA_WDC_WD20EZRX-00_WD-WCC4M1820067-part4  ONLINE       0     0     0
        scsi-SATA_TOSHIBA_DT01ACA_Y3JRP7AGS-part4        ONLINE       0     0     0
        scsi-SATA_WDC_WD20EFRX-68_WD-WMC4M2893309-part4  ONLINE       0     0     0
    logs
      scsi-SATA_KINGSTON_SV300S50026B7743042A5D-part1    ONLINE       0     0     0
    cache
      scsi-SATA_KINGSTON_SV300S50026B7743042A5D-part2    ONLINE       0     0     0

errors: No known data errors
```

```
nexus:
    version: 5000
    name: 'nexus'
    state: 0
    txg: 1047999
    pool_guid: 12739992419793460883
    hostname: 'ubuntu'
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 12739992419793460883
        create_txg: 4
        children[0]:
            type: 'mirror'
            id: 0
            guid: 11198600791703981860
            metaslab_array: 34
            metaslab_shift: 34
            ashift: 12
            asize: 1919294111744
            is_log: 0
            create_txg: 4
            children[0]:
                type: 'disk'
                id: 0
                guid: 5209932698177547192
                path: '/dev/disk/by-id/scsi-SATA_WDC_WD20EZRX-00_WD-WCC4M1820067-part4'
                whole_disk: 0
                DTL: 48
                create_txg: 4
            children[1]:
                type: 'disk'
                id: 1
                guid: 8176591618749386368
                path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA_Y3JRP7AGS-part4'
                whole_disk: 0
                DTL: 47
                create_txg: 4
            children[2]:
                type: 'disk'
                id: 2
                guid: 2843563448944389397
                path: '/dev/disk/by-id/scsi-SATA_WDC_WD20EFRX-68_WD-WMC4M2893309-part4'
                whole_disk: 0
                DTL: 46
                create_txg: 4
                resilvering: 1
        children[1]:
            type: 'disk'
            id: 1
            guid: 13227607038863647726
            path: '/dev/disk/by-id/scsi-SATA_KINGSTON_SV300S50026B7743042A5D-part1'
            whole_disk: 0
            metaslab_array: 87
            metaslab_shift: 25
            ashift: 9
            asize: 3994550272
            is_log: 1
            DTL: 125
            create_txg: 582599
    features_for_read:
```
