### ISSUE TITLE
Intel 730 get ashift=9 although zpool_vdev.c defined INTEL SSDSC2BP48 as ashift=12

### ISSUE THREAD

**Issue by AndCycle** [zfsonlinux/zfs#3025]
I recently bought a Intel 730 480G as root device, haven't thought much about it, just
```
zpool create zroot /dev/sda
```
the device is direct attach to AMD 700 series SATA controller,
smart report 
```
=== START OF INFORMATION SECTION ===
Model Family:     Intel 730 and DC S3500/S3700 Series SSDs
Device Model:     INTEL SSDSC2BP480G4
Serial Number:    BTJR443101K6480BGN
LU WWN Device Id: 5 5cd2e4 04b6fd13a
Firmware Version: L2010420
User Capacity:    480,103,981,056 bytes [480 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 2.6, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Tue Jan 20 15:26:02 2015 CST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

```

zpool get all zroot show ashift=0 as default,

zdb shows
```
MOS Configuration:
        version: 5000
        name: 'zroot'
        state: 0
        txg: 10047907
        pool_guid: 15929196681962393339
        errata: 0
        hostname: 'bacztwo'
        vdev_children: 1
        vdev_tree:
            type: 'root'
            id: 0
            guid: 15929196681962393339
            children[0]:
                type: 'disk'
                id: 0
                guid: 13661443477021649597
                path: '/dev/sda1'
                whole_disk: 1
                metaslab_array: 33
                metaslab_shift: 32
                ashift: 9
                asize: 480088948736
                is_log: 0
                create_txg: 4
        features_for_read:
```

has no idea about what's going on under there
