### ISSUE TITLE
import failure, weird unavail issue

### ISSUE THREAD

**Issue by nevion** [zfsonlinux/zfs#3107]
So I use mpt2sas for my 2 disk arrays.  Since kernel 3.16 or so, there has been some change that causes the drives to export differently under /dev/disk/by-id as such:
ata-TOSHIBA_DT01ACA300_Z2T3B8LAS-part1 -> scsi-SATA_TOSHIBA_DT01ACA3_Z2T3B8LAS-part1

Apparently the way to fix device name based issue this is to fake the death of the drives (one at a time) and replace it with another... like it's self.  I've done this for a number of disks and didn't really encounter an issue until today.  Keep in mind I only was trying to replace the last drive of each raidz group.  Somehow this has resulted in UNAVAIL OFFLINE and now UNAVAIL corrupted data.  The machine has ECC ram and I've not noted anything else out of the ordinary.

The procedure I've been using is to start from a clean boot - auto import of the raid fails because the ata devices do not exist under /dev/disk/by-id.  I then create the symlinks to them based on what zfs status reports for the vdev and what matches the serial numbers and starts with scsi-sata under /dev/disk/by-id.except for the ones which I will be replacing.  I then zfs replace the devices in question - usually I'm greeted with a error saying that drive is still part of the group even though it is marked unavail.  So to get around that I run zfs export, then zfs labelclear vdev and import the pool again.  After that was done today however somehow device 5 (10976772185152087831 and 14507462425068499796) both started reporting unavail and after a couple of reboots it said corrupted data and somehow spread to device 6 in both pools.  I'll also point out somehow the vdev paths it is using change on import (when it is having trouble importing devices) to numbers (like above) and scsi-<numbers> - It has done this (erroneous?) path change all throughout this process of device replacing.

```
zpool import -d /dev/disk/by-id/
   pool: storage
     id: 18405946887743981906
  state: DEGRADED
 status: One or more devices contains corrupted data.
 action: The pool can be imported despite missing or damaged devices.  The
        fault tolerance of the pool may be compromised if imported.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
 config:

        storage                                               DEGRADED
          raidz2-0                                            ONLINE
            scsi-SATA_TOSHIBA_DT01ACA3_Z2T3B8LAS              ONLINE
            scsi-SATA_TOSHIBA_DT01ACA3_Z2T44J4AS-part1        ONLINE
            scsi-SATA_TOSHIBA_DT01ACA3_Z2T4615AS-part1        ONLINE                                                                                  
            scsi-SATA_TOSHIBA_DT01ACA3_Z2T4D24AS-part1        ONLINE                                                                                  
            10976772185152087831                              UNAVAIL  corrupted data                                                                 
            14419488228501462420                              UNAVAIL  corrupted data                                                                 
            13636846573961515177                              UNAVAIL  corrupted data                                                                 
          raidz2-1                                            DEGRADED                                                                                
            scsi-SATA_Hitachi_HDS72303_MS79215X09KLNA-part1   ONLINE
            scsi-SATA_TOSHIBA_DT01ACA3_Z2T25ZYAS-part1        ONLINE
            scsi-SATA_WDC_WD30EFRX-68A_WD-WCC1T0781750-part1  ONLINE
            14507462425068499796                              UNAVAIL  corrupted data
            scsi-35000c5003cd6fffd                            UNAVAIL  corrupted data
            scsi-350014ee2b3051234                            UNAVAIL  corrupted data
            14052951480466135352                              UNAVAIL
```

```
 zdb -e -p /dev/disk/by-id/ storage

Configuration for import:
        vdev_children: 2
        version: 5000
        pool_guid: 18405946887743981906
        name: 'storage'
        state: 0
        vdev_tree:
            type: 'root'
            id: 0
            guid: 18405946887743981906
            children[0]:
                type: 'raidz'
                id: 0
                guid: 98709332956160999
                nparity: 2
                metaslab_array: 30
                metaslab_shift: 37
                ashift: 12
                asize: 21004107120640
                is_log: 0
                create_txg: 4
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 6339672892164796
                    whole_disk: 1
                    DTL: 34
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA3_Z2T3B8LAS-part1'
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 14549786761647193227
                    whole_disk: 0
                    DTL: 4269
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA3_Z2T44J4AS-part1'
                children[2]:
                    type: 'disk'
                    id: 2
                    guid: 7272105023046033440
                    whole_disk: 0
                    DTL: 8195
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA3_Z2T4615AS-part1'
                children[3]:
                    type: 'disk'
                    id: 3
                    guid: 12001441393190676952
                    whole_disk: 0
                    DTL: 8201
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA3_Z2T4D24AS-part1'
                children[4]:
                    type: 'disk'
                    id: 4
                    guid: 10976772185152087831
                    phys_path: '/dev/gpt/TOSH_Z2T5P7MAS'
                    whole_disk: 1
                    not_present: 1
                    DTL: 73
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-35000039ff4c2959c'
                children[5]:
                    type: 'disk'
                    id: 5
                    guid: 14419488228501462420
                    phys_path: '/dev/gpt/TOSH_Z2T5W48AS'
                    whole_disk: 1
                    not_present: 1
                    DTL: 70
                    create_txg: 4
                    path: '/dev/disk/by-id/scsi-0ATA_TOSHIBA_DT01ACA3_Z2T5W48AS'
                children[6]:
                    type: 'disk'
                    id: 6
                    guid: 13636846573961515177
                    path: '/dev/disk/by-id/scsi-35000039ff4c2aff9'
                    phys_path: '/dev/gpt/TOSH_Z2T5X8AAS'
                    whole_disk: 1
                    not_present: 1
                    DTL: 61
                    create_txg: 4
            children[1]:
                type: 'raidz'
                id: 1
                guid: 10985882145574087229
                nparity: 2
                metaslab_array: 24
                metaslab_shift: 37
                ashift: 12
                asize: 21004107120640
                is_log: 0
                create_txg: 30560
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 6945219493890887179
                    whole_disk: 0
                    DTL: 4271
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-SATA_Hitachi_HDS72303_MS79215X09KLNA-part1'
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 17780031005578215372
                    whole_disk: 0
                    DTL: 8200
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-SATA_TOSHIBA_DT01ACA3_Z2T25ZYAS-part1'
                children[2]:
                    type: 'disk'
                    id: 2
                    guid: 2797484648281213392
                    whole_disk: 0
                    DTL: 8203
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-SATA_WDC_WD30EFRX-68A_WD-WCC1T0781750-part1'
                children[3]:
                    type: 'disk'
                    id: 3
                    guid: 14507462425068499796
                    whole_disk: 0
                    not_present: 1
                    DTL: 92
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-35000cca37ec4bd40'
                children[4]:
                    type: 'disk'
                    id: 4
                    guid: 10916108032243682504
                    whole_disk: 0
                    DTL: 91
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-35000c5003cd6fffd'
                children[5]:
                    type: 'disk'
                    id: 5
                    guid: 8076027686180084832
                    whole_disk: 0
                    DTL: 90
                    create_txg: 30560
                    path: '/dev/disk/by-id/scsi-350014ee2b3051234'
                children[6]:
                    type: 'disk'
                    id: 6
                    guid: 14052951480466135352
                    path: '/dev/disk/by-id/scsi-350014ee2b4b6726d'
                    whole_disk: 0
                    not_present: 1
                    DTL: 86
                    create_txg: 30560
zdb: can't open 'storage': No such device or addres
```

I'm completely baffled at this result.  As I poked around and rebooted I've noticed the paths keep changing.  All the devices exist though though - I can cat/dd from them just fine.  

Versions:  zfs-0.6.3_git.1423692317.e02b533 , kernel 3.16.7 on OpenSUSE 13.2.

Where do I go from here?
