### ISSUE TITLE
Allow higher ashift values as command line parameter

### ISSUE THREAD

**Issue by kaazoo** [zfsonlinux/zfs#4205]
I have a iSCSI (multipathed) device which has a physical blocksize of 16 KB:

```
scsi host17: iSCSI Initiator over TCP/IP
scsi 17:0:0:0: Direct-Access     LIO-ORG  IBLOCK           4.0  PQ: 0 ANSI: 5
sd 17:0:0:0: Attached scsi generic sg3 type 0
sd 17:0:0:0: [sdd] 194884141056 512-byte logical blocks: (99.7 TB/90.7 TiB)
sd 17:0:0:0: [sdd] 16384-byte physical blocks
sd 17:0:0:0: [sdd] Write Protect is off
sd 17:0:0:0: [sdd] Mode Sense: 43 00 10 08
sd 17:0:0:0: [sdd] Write cache: enabled, read cache: enabled, supports DPO and FUA
sd 17:0:0:0: [sdd] Attached SCSI disk
```

When I try to specifiy 'ashift=14' for 16 KB blocksize, I get the following error:

```
# zpool create -o ashift=14 pool1 /dev/mapper/mpath98
cannot create 'pool1': property 'ashift' number 14 is invalid.
```

However if I don't specifiy the ashift parameter, I everthing is fine and ZFS even seems to use 'ashift=14':

```
# zpool create live_neu /dev/mapper/mpath98

# zdb
pool1:
    version: 5000
    name: 'pool1'
    state: 0
    txg: 4
    pool_guid: 11624135545234252745
    errata: 0
    hostid: 8323329
    hostname: 'server123'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 11624135545234252745
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 8692662930490887573
            path: '/dev/mapper/mpath98'
            whole_disk: 0
            metaslab_array: 34
            metaslab_shift: 39
            ashift: 14
            asize: 99780675502080
            is_log: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
