### ISSUE TITLE
Zfs not recognising some exported pool

### ISSUE THREAD

**Issue by lorddoskias** [zfsonlinux/zfs#4438]
So I have an exported pool via: `zpool export 'pool-name'`. And when I try to import it again using `zpool import -N -d . pool-name.zfs` I get: `zpool import -N -d . fdhaji56.zfs`. Here is the output of zdb -l fdhaji56.zfs:
```
--------------------------------------------
LABEL 0
--------------------------------------------
    version: 5000
    name: 'uk13.<redacted>.eu-fdhaji56'
    state: 1
    txg: 20
    pool_guid: 16182573769965201466
    errata: 0
    hostname: 'uksmallvault2.<redacted>.net'
    top_guid: 17077420260179023081
    guid: 17077420260179023081
    vdev_children: 1
    vdev_tree:
        type: 'file'
        id: 0
        guid: 17077420260179023081
        path: '/var/backups/uk13.<redacted>.eu/fdhaji56.zfs'
        metaslab_array: 34
        metaslab_shift: 30
        ashift: 9
        asize: 214743646208
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 1
--------------------------------------------
    version: 5000
    name: 'uk13.<redacted>.eu-fdhaji56'
    state: 1
    txg: 20
    pool_guid: 16182573769965201466
    errata: 0
    hostname: 'uksmallvault2.<redacted>.net'
    top_guid: 17077420260179023081
    guid: 17077420260179023081
    vdev_children: 1
    vdev_tree:
        type: 'file'
        id: 0
        guid: 17077420260179023081
        path: '/var/backups/uk13.<redacted>.eu/fdhaji56.zfs'
        metaslab_array: 34
        metaslab_shift: 30
        ashift: 9
        asize: 214743646208
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 2
--------------------------------------------
    version: 5000
    name: 'uk13.<redacted>.eu-fdhaji56'
    state: 1
    txg: 20
    pool_guid: 16182573769965201466
    errata: 0
    hostname: 'uksmallvault2.<redacted>.net'
    top_guid: 17077420260179023081
    guid: 17077420260179023081
vdev_children: 1
    vdev_tree:
        type: 'file'
        id: 0
        guid: 17077420260179023081
        path: '/var/backups/uk13.<redacted>.eu/fdhaji56.zfs'
        metaslab_array: 34
        metaslab_shift: 30
        ashift: 9
        asize: 214743646208
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
--------------------------------------------
LABEL 3
--------------------------------------------
    version: 5000
    name: 'uk13.<redacted>.eu-fdhaji56'
    state: 1
    txg: 20
    pool_guid: 16182573769965201466
    errata: 0
    hostname: 'uksmallvault2.<redacted>.net'
    top_guid: 17077420260179023081
    guid: 17077420260179023081
    vdev_children: 1
    vdev_tree:
        type: 'file'
        id: 0
        guid: 17077420260179023081
        path: '/var/backups/uk13.<redacted>.eu/fdhaji56.zfs'
        metaslab_array: 34
        metaslab_shift: 30
        ashift: 9
        asize: 214743646208
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

However when I try to run any other zdb command I also get an error: 

```
zdb -e -p `pwd` uk13.<redacted>.eu-fdhaji56
zdb: can't open 'uk13.<redacted>.eu-fdhaji56': No such file or directory
```

Here is the version of the modules: 
```
modinfo zfs | grep version
version:        0.6.5-1
srcversion:     67C0DDE0E3BBC0A94D80FD8
vermagic:       4.4.1-clouder2 SMP mod_unload modversions 
modinfo spl | grep versio
version:        0.6.5-1
srcversion:     6645C8E5BDEF665A9FAD3CF
vermagic:       4.4.1-clouder2 SMP mod_unload modversions 
```

The strange thing is this happen only on some exported pools and not on others. So far I have no idea what might be causing this nor what information to provide to be able to debug it further, any assistance would be very much appreciated.
