### ISSUE TITLE
Execution of 'zdb' results in coredump

### ISSUE THREAD

**Issue by minorsatellite** [zfsonlinux/zfs#6329]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.04
Linux Kernel                 |  4.4.0-62-generic
Architecture                 |  64bit
ZFS Version                  |  0.6.5.6-0ubuntu15
SPL Version                  |  0.6.5.6-0ubuntu15 

### Describe the problem you're observing

Execute 'zdb' command with/without any supported flags/arguments results in core dump

### Describe how to reproduce the problem

root@host:/home/storage-admin# zdb zpool1
Aborted (core dumped)

**Comment by loli10K** [comment]
Is this still an issue? I cannot reproduce it here with the commands provided, this may be specific to your setup:

```
root@xenial:~# uname -r
4.4.0-62-generic
root@xenial:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
root@xenial:~# zdb 
rpool:
    version: 5000
    name: 'rpool'
    state: 0
    txg: 927
    pool_guid: 6578963701138440634
    errata: 0
    hostname: 'xenial'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 6578963701138440634
        children[0]:
            type: 'disk'
            id: 0
            guid: 14267708115974669646
            path: '/dev/vda1'
            whole_disk: 0
            metaslab_array: 35
            metaslab_shift: 26
            ashift: 12
            asize: 10723000320
            is_log: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
root@xenial:~# 
```

The thing about coredumps is they usually store a lot of interesting information about the problem, if you can still reproduce the crash we have the opportunity to debug this: install `zfsutils-linux-dbg` and get a backtrace from the core.
