### ISSUE TITLE
zpool import blind to a lonely vdev from 3-way mirror

### ISSUE THREAD

**Issue by clefru** [zfsonlinux/zfs#6588]
### Describe the problem you're observing
I ripped a disk from an existing 3-way mirror and moved to a new machine. There I expect the pool to show up on `zpool import`, but it does not. I don't understand why that is.

zdb sees the labels on the disk. stracing `zpool import` shows that the disk is opened and read from. I expect zpool import to report the pool at least as broken.

In the zdb dump below, disk with id 0 and 1 are missing. Disk with id 2 is present. If somebody could provide me with an interpretation of "create_txg" and "DTL" in the zdb, that would be nice, as this seems to be a difference between the disk 0/1 and 2.

Is there any way to drill down further? Can I make zpool more verbose to see why the labels on that device are rejected? Thank you.

(I am on 0.7.0-rc5. Reading the commits between 0.7.1 and 0.7.0-rc5 doesn't seem like that they are relevant.)

### Include any warning/errors/backtraces from the system logs

```
[root@irulan:/dev/shm]# zdb -l /dev/mapper/LUKS-9d45e1d2-ffb2-42da-9a1a-bb3272fe60f2 
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'z'
    state: 0
    txg: 0
    pool_guid: 15948580017589837828
    errata: 0
    hostid: 2112949952
    hostname: 'nixos'
    top_guid: 3021567172465303999
    guid: 17510751656877362070
    vdev_children: 1
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 3021567172465303999
        whole_disk: 0
        metaslab_array: 31
        metaslab_shift: 34
        ashift: 12
        asize: 4000510640128
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 2796918174589723099
            path: '/dev/disk/by-id/dm-uuid-CRYPT-LUKS1-c7b0e5a217fd4a8080821902c4dee069-LUKS-c7b0e5a2-17fd-4a80-8082-1902c4dee069'
            whole_disk: 0
            DTL: 48
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 66752805618382679
            path: '/dev/disk/by-id/dm-uuid-CRYPT-LUKS1-9448350c7c9c4094831c16f9c2f052a4-LUKS-9448350c-7c9c-4094-831c-16f9c2f052a4'
            whole_disk: 0
            DTL: 49
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 17510751656877362070
            path: '/dev/mapper/LUKS-9d45e1d2-ffb2-42da-9a1a-bb3272fe60f2'
            whole_disk: 0
            DTL: 403
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    create_txg: 0
    labels = 0 1 2 3 

[root@irulan:/dev/shm]# zpool import z
cannot import 'z': no such pool available

[root@irulan:/dev/shm]# zpool import 15948580017589837828 
cannot import '15948580017589837828': no such pool available

[root@irulan:/dev/shm]# zpool import 17510751656877362070
cannot import '17510751656877362070': no such pool available
```
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | nixos
Distribution Version    | 17.03
Linux Kernel                 | 4.9.45
Architecture                 | x86_64
ZFS Version                  | 0.7.0-rc5
SPL Version                  | 0.7.0-rc5
