### ISSUE TITLE
Slow writes to pool created by FreeNAS

### ISSUE THREAD

**Issue by PeterFeicht** [zfsonlinux/zfs#6626]
I'm trying to write to a pool created by FreeNAS using ZFS on Linux ([details here](https://forums.freenas.org/index.php?threads/recover-thecus-raid5-on-freenas.50277/#post-399804)), which works fine.

However, after copying some stuff over, about the same amount as I have RAM in that machine, writing to the ZFS volume gets really slow, like 30MB/s to a raidz2 with 8 drives. Write speeds are not that great to begin with, just 150 to 200MB/s. I don't know whether this is a configuration/usage issue or a proper bug, so any input would be appreciated.

I noticed the `arc_reclaim` process hogging some CPU, which made me think this might be related to issue #6531 somehow. I don't have anything valuable on the pool yet, so I can do whatever is necessary for troubleshooting.

## Hardware:

What        | Model
----------- | -----
Motherboard | Intel S5520UR
CPU         | Dual Xeon L5640
RAM         | 96GB DDR3 ECC
HBA         | LSI SAS9207-4i4e (cross-flashed from HP H222), firmware version P20
Drives      | 8x WD80EFZX

## Linux: Arch Linux

ZFS installed from [archzfs](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#archzfs) repo.

What            | Version
--------------- | -------
Linux Kernel    | 4.12.10-1
ZFS             | 0.7.1-1
SPL             | 0.7.1-1

`zpool status` output:

```
  pool: tank
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 0h6m with 0 errors on Mon Aug 28 20:02:07 2017
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          raidz2-0  ONLINE       0     0     0
            sdb     ONLINE       0     0     0
            sdc     ONLINE       0     0     0
            sda     ONLINE       0     0     0
            sdf     ONLINE       0     0     0
            sde     ONLINE       0     0     0
            sdd     ONLINE       0     0     0
            sdg     ONLINE       0     0     0
            sdh     ONLINE       0     0     0

errors: No known data errors
```

`zdb` output:

```
tank:
    version: 5000
    name: 'tank'
    state: 0
    txg: 8054
    pool_guid: 6775885842032388289
    errata: 0
    hostname: 'antares'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 6775885842032388289
        children[0]:
            type: 'raidz'
            id: 0
            guid: 6686971514524699808
            nparity: 2
            metaslab_array: 45
            metaslab_shift: 39
            ashift: 12
            asize: 63995287437312
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 36
            children[0]:
                type: 'disk'
                id: 0
                guid: 18032278711795630256
                path: '/dev/sdb2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@1/elmdesc@SLOT_001'
                whole_disk: 1
                DTL: 64
                create_txg: 4
                com.delphix:vdev_zap_leaf: 37
            children[1]:
                type: 'disk'
                id: 1
                guid: 13530303699855493619
                path: '/dev/sdc2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@3/elmdesc@SLOT_003'
                whole_disk: 1
                DTL: 63
                create_txg: 4
                com.delphix:vdev_zap_leaf: 38
            children[2]:
                type: 'disk'
                id: 2
                guid: 15037164158216564558
                path: '/dev/sda2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@2/elmdesc@SLOT_002'
                whole_disk: 1
                DTL: 62
                create_txg: 4
                com.delphix:vdev_zap_leaf: 39
            children[3]:
                type: 'disk'
                id: 3
                guid: 5640001431923885195
                path: '/dev/sdf2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@6/elmdesc@SLOT_006'
                whole_disk: 1
                DTL: 61
                create_txg: 4
                com.delphix:vdev_zap_leaf: 40
            children[4]:
                type: 'disk'
                id: 4
                guid: 18025663285868450324
                path: '/dev/sde2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@5/elmdesc@SLOT_005'
                whole_disk: 1
                DTL: 60
                create_txg: 4
                com.delphix:vdev_zap_leaf: 41
            children[5]:
                type: 'disk'
                id: 5
                guid: 1150609568386899083
                path: '/dev/sdd2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@4/elmdesc@SLOT_004'
                whole_disk: 1
                DTL: 59
                create_txg: 4
                com.delphix:vdev_zap_leaf: 42
            children[6]:
                type: 'disk'
                id: 6
                guid: 3578974144461137932
                path: '/dev/sdg2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@7/elmdesc@SLOT_007'
                whole_disk: 1
                DTL: 58
                create_txg: 4
                com.delphix:vdev_zap_leaf: 43
            children[7]:
                type: 'disk'
                id: 7
                guid: 14532033329246330435
                path: '/dev/sdh2'
                phys_path: 'id1,enc@n500019b9ff4c5e3e/type@0/slot@8/elmdesc@SLOT_008'
                whole_disk: 1
                DTL: 57
                create_txg: 4
                com.delphix:vdev_zap_leaf: 44
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

## BSD: FreeNAS 11.0-U2

What            | Version
--------------- | -------
FreeBSD Kernel  | 11.0-STABLE
ZFS             | ??

`zpool status` output:

```
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 0h6m with 0 errors on Mon Aug 28 20:02:07 2017
config:

        NAME                                            STATE     READ WRITE CKSUM
        tank                                            ONLINE       0     0     0
          raidz2-0                                      ONLINE       0     0     0
            gptid/c072ac4d-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c11dfad2-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c1d5c249-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c290fa3e-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c33d7a88-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c3dad10f-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c4832b2f-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0
            gptid/c5226b94-8c10-11e7-bda6-001517bd58c0  ONLINE       0     0     0

errors: No known data errors
```

`zdb` refuses to acknowledge that `tank` exists:

```
zdb: can't open 'tank': No such file or directory

ZFS_DBGMSG(zdb):
```
