### ISSUE TITLE
Small issue with netplan config: Ubuntu 17.10 Root on ZFS

### ISSUE THREAD

**Issue by callumgare** [zfsonlinux/zfs#7137]
The netplan config in section 4.2 of the wiki page "Ubuntu 17.10 Root on ZFS" has particular link name. Instead of reading:
````
# vi /mnt/etc/netplan/NAME.yaml
network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
````
It should read:
````
# vi /mnt/etc/netplan/NAME.yaml
network:
  version: 2
  ethernets:
    NAME:
      dhcp4: true
````
So that people know to update the link name to reflect that of their system. Tripped me up for a bit :P
