### ISSUE TITLE
Question about "refcount mismatch"

### ISSUE THREAD

**Issue by mabod** [zfsonlinux/zfs#7204]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Manjaro
Distribution Version    |  rolling release
Linux Kernel                 |  4.15.4
Architecture                 |  amd64
ZFS Version                  |  0.7.5-1
SPL Version                  | 0.7.5-1

I find a handful of issues here related to "refcount mismatch" but reading them was not helping me to understand the urgency of a message like  `space map refcount mismatch: expected 240 != actual 232`

### Describe the problem you're observing

My pool zstore is not having issues according to zpool status:

```
27# zpool status zstore
  pool: zstore
 state: ONLINE
  scan: scrub repaired 0B in 4h19m with 0 errors on Sun Feb 11 21:13:50 2018
config:

	NAME                 STATE     READ WRITE CKSUM
	zstore               ONLINE       0     0     0
	  mirror-0           ONLINE       0     0     0
	    WD-WCC4E5HF3P4S  ONLINE       0     0     0
	    WD-WCC4E1SSP28F  ONLINE       0     0     0
	  mirror-1           ONLINE       0     0     0
	    WD-WCC4E1SSP6NC  ONLINE       0     0     0
	    WD-WCC7K7EK9VC4  ONLINE       0     0     0

errors: No known data errors
```

But `zdb -u` is reporting a `refcount mismatch`

```
Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 161284
	guid_sum = 7197309111221853808
	timestamp = 1519192594 UTC = Wed Feb 21 06:56:34 2018
	mmp_magic = 00000000a11cea11
	mmp_delay = 0

space map refcount mismatch: expected 240 != actual 232
```
I excecuted `zdb -mc zstore` in the hope that this issue gets fixed but it doesnt help. The output at the end looks like this:

```
Traversing all blocks to verify metadata checksums and verify nothing leaked ...

loading space map for vdev 1 of 2, metaslab 115 of 116 ...
2.93T completed (3378MB/s) estimated time remaining: 0hr 00min 08sec          
	No leaks (block sum matches space maps exactly)

	bp count:         4527224
	ganged count:           0
	bp logical:    3372952921600      avg: 745037
	bp physical:   3245456411136      avg: 716875     compression:   1.04
	bp allocated:  3247705292800      avg: 717372     compression:   1.04
	bp deduped:             0    ref>1:      0   deduplication:   1.00
	SPA allocated: 3247705292800     used: 40.74%

	additional, non-pointer bps of type 0:      51561
	Dittoed blocks on same vdev: 127212

space map refcount mismatch: expected 240 != actual 232
```
So my questions are:

- Is this pool in trouble? 
- How am I supposed to deal with this? Any cure?

Thanks
Matthias

**Comment by behlendorf** [comment]
> Is this pool in trouble?

It depends.  This may be harmless if you're running `zdb` on an active imported pool.  To determine for certain if there's an issue make sure you export the pool then run `zdb` on it and see if it detects the same problem.

> How am I supposed to deal with this? Any cure?

If you still observe the issue it means that the spacemaps describing the free space in your pool have somehow been damaged.  Currently the only guarenteed cure for this is to use `zfs send/recv` to copy the contents of the exiting pool to a newly created pool on different devices.

**Comment by mabod** [comment]
> export the pool then run zdb on it

I dont know what you mean. When I export the pool and run `zbd -u zstore` 

`zdb: can't open 'zstore': No such file or directory`

and `zdb -ue zstore` says:

`zdb: can't open 'zstore': File exists`

If I move ` /etc/zfs/zpool.cache` and try `zdb -ue zstore` again it gives the same error:

```
Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 162321
	guid_sum = 7197309111221853808
	timestamp = 1519278560 UTC = Thu Feb 22 06:49:20 2018
	mmp_magic = 00000000a11cea11
	mmp_delay = 0

space map refcount mismatch: expected 240 != actual 232
```

**Comment by mabod** [comment]
I succeeded somehow to get zdb output from the exported pool. I moved `/etc/zfs/zpool.cache` and ran `zdb -eC zstore`: This gives the same `space map refcount mismatch`:

```
1# zdb -eC zstore

MOS Configuration:
        version: 5000
        name: 'zstore'
        state: 1
        txg: 162390
        pool_guid: 14393956364711311496
        errata: 0
        hostid: 4294967295
        hostname: 'rakete'
        com.delphix:has_per_vdev_zaps
        vdev_children: 2
        vdev_tree:
            type: 'root'
            id: 0
            guid: 14393956364711311496
            children[0]:
                type: 'mirror'
                id: 0
                guid: 6083005762724255950
                metaslab_array: 259
                metaslab_shift: 35
                ashift: 12
                asize: 4000771997696
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 129
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 2998250447430390224
                    path: '/dev/disk/by-vdev/WD-WCC4E5HF3P4S-part1'
                    devid: 'ata-WDC_WD40EZRZ-00WN9B0_WD-WCC4E5HF3P4S-part1'
                    phys_path: 'pci-0000:00:17.0-ata-2'
                    whole_disk: 1
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 130
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 8762276478183427200
                    path: '/dev/disk/by-vdev/WD-WCC4E1SSP28F-part1'
                    devid: 'ata-WDC_WD40EZRZ-00WN9B0_WD-WCC4E1SSP28F-part1'
                    phys_path: 'pci-0000:00:17.0-ata-3'
                    whole_disk: 1
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 131
            children[1]:
                type: 'mirror'
                id: 1
                guid: 3605884340580067442
                metaslab_array: 256
                metaslab_shift: 35
                ashift: 12
                asize: 4000771997696
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 132
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 15809553155304475366
                    path: '/dev/disk/by-vdev/WD-WCC4E1SSP6NC-part1'
                    devid: 'ata-WDC_WD40EZRZ-00WN9B0_WD-WCC4E1SSP6NC-part1'
                    phys_path: 'pci-0000:00:17.0-ata-4'
                    whole_disk: 1
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 133
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 10884614783416580978
                    path: '/dev/disk/by-vdev/WD-WCC7K7EK9VC4-part1'
                    devid: 'ata-WDC_WD40EZRZ-00GXCB0_WD-WCC7K7EK9VC4-part1'
                    phys_path: 'pci-0000:00:17.0-ata-1'
                    whole_disk: 1
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 134
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data
space map refcount mismatch: expected 240 != actual 232
```
So you say this pool is in trouble? What next?
