### ISSUE TITLE
Healthy mirror/plex pool in 0.7.1 will not import after upgrade to 0.7.5

### ISSUE THREAD

**Issue by AeonJJohnson** [zfsonlinux/zfs#7455]
### System information
Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | RHEL 
Distribution Version    | 7.4.1708
Linux Kernel                | 3.10.0-693.21.1.el7.x86_64
Architecture                 | x86_64
ZFS Version                  | 0.7.5-1
SPL Version                 | 0.7.5-1

### Describe the problem you're observing
Healthy 20-drive mirror/plex zpool will not import after update of kernel from 3.10.0-693.2.2.el7.x86_64 to 3.10.0-693.21.1.el7.x86_64 and updating SPL/ZFS from 0.7.1-1 to 0.7.5-1 via yum/dkms update. Several different import approaches have been attempted, all have failed with 'no zpool available for import'. Imports attempted with/without multipath, targeting import directories (by-vdev, mapper, /dev), import by poolname, import by pool GUID, rw and readonly modes, recovery import (-F). All fail with same result.

### Describe how to reproduce the problem
Update from/to kernel versions and SPL/ZFS versions as noted above.

### Include any warning/errors/backtraces from the system logs
No warnings/errors/backtraces in logs. zfs/dbgmsg comes up empty. An strace of an import attempt is up on pastebin (seemed too long to post here):
```
https://pastebin.com/NQZ1zxYY
```
Here is the tail end of the strace (entirety is on pastebin, link above)
```
open("/etc/udev/udev.conf", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=49, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "# see udev.conf(5) for details\n\n"..., 4096) = 49
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
lstat("/dev", {st_mode=S_IFDIR|0755, st_size=5280, ...}) = 0
lstat("/dev/sdu", {st_mode=S_IFBLK|0660, st_rdev=makedev(65, 64), ...}) = 0
stat("/sys/subsystem/block/devices/sdu", 0x7ffc1166cea0) = -1 ENOENT (No such file or directory)
stat("/sys/bus/block/devices/sdu", 0x7ffc1166cea0) = -1 ENOENT (No such file or directory)
stat("/sys/class/block/sdu", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
readlink("/sys/class/block/sdu", "../../devices/pci0000:80/0000:80"..., 1024) = 140
stat("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:20/end_device-4:0:20/target4:0:20/4:0:20:0/block/sdu/uevent", {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
readlink("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:20/end_device-4:0:20/target4:0:20/4:0:20:0/block/sdu/subsystem", "../../../../../../../../../../.."..., 1024) = 50
open("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:20/end_device-4:0:20/target4:0:20/4:0:20:0/block/sdu/uevent", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "MAJOR=65\nMINOR=64\nDEVNAME=sdu\nDE"..., 4096) = 43
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
open("/run/udev/data/b65:64", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=1237, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "S:disk/by-id/scsi-355cd2e414dc3b"..., 4096) = 1237
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
open("/etc/udev/udev.conf", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=49, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "# see udev.conf(5) for details\n\n"..., 4096) = 49
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
lstat("/dev", {st_mode=S_IFDIR|0755, st_size=5280, ...}) = 0
lstat("/dev/sdv", {st_mode=S_IFBLK|0660, st_rdev=makedev(65, 80), ...}) = 0
stat("/sys/subsystem/block/devices/sdv", 0x7ffc1166cea0) = -1 ENOENT (No such file or directory)
stat("/sys/bus/block/devices/sdv", 0x7ffc1166cea0) = -1 ENOENT (No such file or directory)
stat("/sys/class/block/sdv", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
readlink("/sys/class/block/sdv", "../../devices/pci0000:80/0000:80"..., 1024) = 140
stat("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:21/end_device-4:0:21/target4:0:21/4:0:21:0/block/sdv/uevent", {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
readlink("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:21/end_device-4:0:21/target4:0:21/4:0:21:0/block/sdv/subsystem", "../../../../../../../../../../.."..., 1024) = 50
open("/sys/devices/pci0000:80/0000:80:02.0/0000:81:00.0/host4/port-4:0/expander-4:0/port-4:0:21/end_device-4:0:21/target4:0:21/4:0:21:0/block/sdv/uevent", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "MAJOR=65\nMINOR=80\nDEVNAME=sdv\nDE"..., 4096) = 43
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
open("/run/udev/data/b65:80", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=1235, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "S:disk/by-id/scsi-355cd2e414dc3b"..., 4096) = 1235
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
ioctl(3, _IOC(0, 0x5a, 0x05, 0x00), 0x7ffc1166b210) = -1 ENOENT (No such file or directory)
ioctl(3, _IOC(0, 0x5a, 0x06, 0x00), 0x7ffc1166b2c0) = 0
open("/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=2502, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd0d3fae000
read(7, "# Locale name alias data base.\n#"..., 4096) = 2502
read(7, "", 4096)                       = 0
close(7)                                = 0
munmap(0x7fd0d3fae000, 4096)            = 0
open("/usr/share/locale/en_US/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/zfs-linux-user.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "cannot import 'lustre-mds': no s"..., 51cannot import 'lustre-mds': no such pool available
) = 51
close(3)                                = 0
close(4)                                = 0
close(5)                                = 0
close(6)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

Since 3.10.0-693.21.1.el7.x86_64 is kernel with RH implemented CVEs for Spectre and Meltdown I disabled them using 'spectre_v2=off nopti' kernel boot args on the chance there was some interference. No change.

**Comment by AeonJJohnson** [comment]
Follow-up, here is a label from one of the drives in the pool. All drives are present and accessible.
```
# zdb -l /dev/sda
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'lustre-mds'
    state: 2
    txg: 5311966
    pool_guid: 8338258131881761712
    errata: 0
    hostid: 1330851904
    hostname: 'mds-01'
    top_guid: 8422072903312607524
    guid: 16139127509716797779
    vdev_children: 10
    vdev_tree:
        type: 'mirror'
        id: 0
        guid: 8422072903312607524
        metaslab_array: 171
        metaslab_shift: 32
        ashift: 9
        asize: 480099172352
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 16139127509716797779
            path: '/dev/disk/by-id/dm-uuid-mpath-355cd2e414dc3df9c'
            devid: 'dm-uuid-mpath-355cd2e414dc3df9c'
            phys_path: 'A0'
            vdev_enc_sysfs_path: '/sys/class/enclosure/4:0:22:0/Disk001'
            whole_disk: 0
            DTL: 225
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 15549948174111978427
            path: '/dev/disk/by-id/dm-uuid-mpath-355cd2e414dd7f469'
            devid: 'dm-uuid-mpath-355cd2e414dd7f469'
            phys_path: 'A1'
            vdev_enc_sysfs_path: '/sys/class/enclosure/4:0:22:0/Disk002'
            whole_disk: 0
            DTL: 224
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1 2 3
```
