### ISSUE TITLE
Lots of 'attempt to access beyond end of device' in syslog

### ISSUE THREAD

**Issue by gedia** [zfsonlinux/zfs#7724]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Gentoo
Distribution Version	| rolling
Linux Kernel	| 4.17.6-gentoo
Architecture	| amd64
ZFS Version	| 0.7.0-1472_g2e5dc449
SPL Version	| 0.7.0-1472_g2e5dc449

### Describe the problem you're observing
My system log is inundated with warnings of attempts to access beyond end of device. This has been the case with previous zfs versions as well, dating back to a couple of months when the system was first built. Here's an example:

> Jul 17 17:26:29 laptop kernel: attempt to access beyond end of device
> Jul 17 17:26:29 laptop kernel: nvme0n1p1: rw=0, want=1000193568, limit=1000062976
> Jul 17 17:26:29 laptop kernel: attempt to access beyond end of device
> Jul 17 17:26:29 laptop kernel: nvme0n1p1: rw=0, want=1000194080, limit=1000062976

With high I/O load, I'm also experiencing some stability issues, but I'm not sure this is in any way related to ZFS or not.

Please let me know how I can provide more useful debugging information.

### Describe how to reproduce the problem
The errors are very frequent, about 1 per second on average (they actually come in bursts). They even appear when the system is generally idle, so I'm not sure what the trigger is.

My system has a few particularities I'd like to list here:
* I only have a single ZFS pool, which comprises of a single partition on an NVMe SSD.
* Before creating the pool, I reformatted the SSD using nvme-cli, and changed its (firmware toggle-able) logical addressing to 4096-byte sectors
* I then created the pool on the entire drive, in order to have the 'whole-disk' flag set
* This created a GPT partition table with two partitions. The smaller of the two (with id=9) is used as an EFI system partition
* I'm using native ZFS encryption on all datasets mounted on VFS. Cipher mode is aes-256-gcm

**Comment by richardelling** [comment]
Can you look at the comments in https://github.com/zfsonlinux/zfs/pull/7629 to see if it applies?
One other method is to look at the asize for the vdev in the label using `zdb -l /dev/nvme0n1` and compare to the partition size of /dev/nvme0n1p1.

A workaround might be as simple as removing partition 9 (it isn't in use) and growing partition 1 to
a large enough size.

**Comment by gedia** [comment]
Thank you for your reply @richardelling 

Here's a report from my system with the values in question:

Device|Start|End|Sectors (count)|Bytes
-|-|-|-|-
nvme0n1|-|-|125026902|512110190592
nvme0n1p1|2048|125009919|125007872|512032243712
nvme0n1p9|125009920|125026303|16384|67108864
vdev|-|-|-|512027525120

I seems to be that the vdev size is smaller than the size of partition 1, so now the 'beyond end of device' error baffles me even more...

I'm not sure how #7629 is related to this... Could you elaborate?

Lastly, I'm actually using partition 9 as the EFI system partition (I'm using EFISTUB for booting), so if I delete it I'll end up with an unbootable system.

And here's the full output of 'zdb -l' for reference. Is it normal to have two labels with identical data?

```
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'gtank'
    state: 0
    txg: 556610
    pool_guid: 15423420548484792682
    errata: 0
    hostid: 8323328
    hostname: 'gdiamantopoulos-laptop'
    top_guid: 9629493302233033777
    guid: 9629493302233033777
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 9629493302233033777
        path: '/dev/disk/by-id/nvme-KXG50ZNV512G_NVMe_TOSHIBA_512GB_184F74BGFQCS-part1'
        devid: 'nvme-KXG50ZNV512G_NVMe_TOSHIBA_512GB_184F74BGFQCS-part1'
        whole_disk: 1
        metaslab_array: 65
        metaslab_shift: 32
        ashift: 13
        asize: 512027525120
        is_log: 0
        DTL: 295
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1 
------------------------------------
LABEL 2
------------------------------------
    version: 5000
    name: 'gtank'
    state: 0
    txg: 235364
    pool_guid: 15423420548484792682
    errata: 0
    hostname: 'gdiamantopoulos-laptop'
    top_guid: 9629493302233033777
    guid: 9629493302233033777
    vdev_children: 1
    vdev_tree:
        type: 'disk'
        id: 0
        guid: 9629493302233033777
        path: '/dev/disk/by-id/nvme-KXG50ZNV512G_NVMe_TOSHIBA_512GB_184F74BGFQCS-part1'
        devid: 'nvme-KXG50ZNV512G_NVMe_TOSHIBA_512GB_184F74BGFQCS-part1'
        whole_disk: 1
        metaslab_array: 65
        metaslab_shift: 32
        ashift: 13
        asize: 512027525120
        is_log: 0
        create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 2 3 
```
