### ISSUE TITLE
Trying to read past end of partition since upgrade to 0.7.10-1 from zfs-0.7.9-1

### ISSUE THREAD

**Issue by mas-dse-pjmulroo** [zfsonlinux/zfs#7899]
### System information
Type | Dell R730XD
 --- | --- 
Distribution Name	|  CentOS Linux release
Distribution Version	|  7.5.1804
Linux Kernel	| 3.10.0-862.11.6
Architecture	| x86_64
ZFS Version	| 0.7.10.1
SPL Version	| 0.7.10.1

### Describe the problem you're observing
Since the upgrade I now see thousands of attempt to access beyond the end of the partition in the kernel logs. Not happening on all systems running 0.7.10.1, only this one. Firmware updates also recently applied to this system. The data is still accessible, but a scrub causes the zpool to report as degraded.
 

### Describe how to reproduce the problem
Upgrade zpool from 0.7.9.1 to 0.7.10.1.

### Include any warning/errors/backtraces from the system logs

```
[ 1738.451499] attempt to access beyond end of device
[1738.451503] sdc1: rw=0, want=19396537888, limit=19396395008
```
```
# zpool status
  pool: data
 state: DEGRADED
status: One or more devices are faulted in response to persistent errors.
        Sufficient replicas exist for the pool to continue functioning in a
        degraded state.
action: Replace the faulted device, or use 'zpool clear' to mark the device
        repaired.
  scan: scrub canceled on Thu Sep 13 12:20:20 2018
config:

        NAME                        STATE     READ WRITE CKSUM
        data                        DEGRADED     0     0     0
          raidz2-0                  DEGRADED     0     0     0
            scsi-35000cca2517d26b0  FAULTED      0     0     0  too many errors
            scsi-35000cca25192f634  FAULTED      0     0     0  too many errors
            scsi-35000cca2519b30b8  DEGRADED     0     0     0  too many errors
            scsi-35000cca251a0f35c  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b1f974  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b3d758  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b4ff10  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b628dc  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b7fc90  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b7fcb8  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b813f0  DEGRADED     0     0     0  too many errors
            scsi-35000cca251b89ad8  DEGRADED     0     0     0  too many errors

errors: No known data errors

```

```
# zdb -l /dev/sdc1
------------------------------------
LABEL 0
------------------------------------
    version: 5000
    name: 'data'
    state: 0
    txg: 13621643
    pool_guid: 13653965617326084904
    errata: 0
    hostname: 'xxxxxxx001'
    top_guid: 10472840087923154775
    guid: 14595263177298823159
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 10472840087923154775
        nparity: 2
        metaslab_array: 34
        metaslab_shift: 40
        ashift: 12
        asize: 119171394306048
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 7413427877862177947
            path: '/dev/disk/by-id/scsi-35000cca2517d26b0-part1'
            devid: 'scsi-35000cca2517d26b0-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:10:0'
            whole_disk: 1
            DTL: 50
            create_txg: 4
            faulted: 1
        children[1]:
            type: 'disk'
            id: 1
            guid: 4040028032609220667
            path: '/dev/disk/by-id/scsi-35000cca25192f634-part1'
            devid: 'scsi-35000cca25192f634-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:8:0'
            whole_disk: 1
            DTL: 49
            create_txg: 4
            faulted: 1
        children[2]:
            type: 'disk'
            id: 2
            guid: 1290194857527223
            path: '/dev/disk/by-id/scsi-35000cca2519b30b8-part1'
            devid: 'scsi-35000cca2519b30b8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:3:0'
            whole_disk: 1
            DTL: 48
            create_txg: 4
            degraded: 1
        children[3]:
            type: 'disk'
            id: 3
            guid: 13501896648859985967
            path: '/dev/disk/by-id/scsi-35000cca251a0f35c-part1'
            devid: 'scsi-35000cca251a0f35c-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:0:0'
            whole_disk: 1
            DTL: 47
            create_txg: 4
            degraded: 1
        children[4]:
            type: 'disk'
            id: 4
            guid: 3357380763939108962
            path: '/dev/disk/by-id/scsi-35000cca251b1f974-part1'
            devid: 'scsi-35000cca251b1f974-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:7:0'
            whole_disk: 1
            DTL: 46
            create_txg: 4
            degraded: 1
        children[5]:
            type: 'disk'
            id: 5
            guid: 5652768500579680387
            path: '/dev/disk/by-id/scsi-35000cca251b3d758-part1'
            devid: 'scsi-35000cca251b3d758-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:9:0'
            whole_disk: 1
            DTL: 45
            create_txg: 4
            degraded: 1
        children[6]:
            type: 'disk'
            id: 6
            guid: 9408909243862883736
            path: '/dev/disk/by-id/scsi-35000cca251b4ff10-part1'
            devid: 'scsi-35000cca251b4ff10-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:6:0'
            whole_disk: 1
            DTL: 44
            create_txg: 4
            degraded: 1
        children[7]:
            type: 'disk'
            id: 7
            guid: 7861725104108086664
            path: '/dev/disk/by-id/scsi-35000cca251b628dc-part1'
            devid: 'scsi-35000cca251b628dc-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:4:0'
            whole_disk: 1
            DTL: 43
            create_txg: 4
            degraded: 1
        children[8]:
            type: 'disk'
            id: 8
            guid: 4321711607497316541
            path: '/dev/disk/by-id/scsi-35000cca251b7fc90-part1'
            devid: 'scsi-35000cca251b7fc90-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:11:0'
            whole_disk: 1
            DTL: 42
            create_txg: 4
            degraded: 1
        children[9]:
            type: 'disk'
            id: 9
            guid: 15176184833201537495
            path: '/dev/disk/by-id/scsi-35000cca251b7fcb8-part1'
            devid: 'scsi-35000cca251b7fcb8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:1:0'
            whole_disk: 1
            DTL: 41
            create_txg: 4
            degraded: 1
        children[10]:
            type: 'disk'
            id: 10
            guid: 9932103074347746317
            path: '/dev/disk/by-id/scsi-35000cca251b813f0-part1'
            devid: 'scsi-35000cca251b813f0-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:5:0'
            whole_disk: 1
            DTL: 40
            create_txg: 4
            degraded: 1
        children[11]:
            type: 'disk'
            id: 11
            guid: 14595263177298823159
            path: '/dev/disk/by-id/scsi-35000cca251b89ad8-part1'
            devid: 'scsi-35000cca251b89ad8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:2:0'
            whole_disk: 1
            DTL: 39
            create_txg: 4
            degraded: 1
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 0 1
------------------------------------
LABEL 2
------------------------------------
    version: 5000
    name: 'data'
    state: 0
    txg: 13487443
    pool_guid: 13653965617326084904
    errata: 0
    hostname: 'xxxxxxxx001'
    top_guid: 10472840087923154775
    guid: 14595263177298823159
    vdev_children: 1
    vdev_tree:
        type: 'raidz'
        id: 0
        guid: 10472840087923154775
        nparity: 2
        metaslab_array: 34
        metaslab_shift: 40
        ashift: 12
        asize: 119171394306048
        is_log: 0
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 7413427877862177947
            path: '/dev/disk/by-id/scsi-35000cca2517d26b0-part1'
            devid: 'scsi-35000cca2517d26b0-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:10:0'
            whole_disk: 1
            DTL: 50
            create_txg: 4
        children[1]:
            type: 'disk'
            id: 1
            guid: 4040028032609220667
            path: '/dev/disk/by-id/scsi-35000cca25192f634-part1'
            devid: 'scsi-35000cca25192f634-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:8:0'
            whole_disk: 1
            DTL: 49
            create_txg: 4
        children[2]:
            type: 'disk'
            id: 2
            guid: 1290194857527223
            path: '/dev/disk/by-id/scsi-35000cca2519b30b8-part1'
            devid: 'scsi-35000cca2519b30b8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:3:0'
            whole_disk: 1
            DTL: 48
            create_txg: 4
        children[3]:
            type: 'disk'
            id: 3
            guid: 13501896648859985967
            path: '/dev/disk/by-id/scsi-35000cca251a0f35c-part1'
            devid: 'scsi-35000cca251a0f35c-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:0:0'
            whole_disk: 1
            DTL: 47
            create_txg: 4
        children[4]:
            type: 'disk'
            id: 4
            guid: 3357380763939108962
            path: '/dev/disk/by-id/scsi-35000cca251b1f974-part1'
            devid: 'scsi-35000cca251b1f974-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:7:0'
            whole_disk: 1
            DTL: 46
            create_txg: 4
        children[5]:
            type: 'disk'
            id: 5
            guid: 5652768500579680387
            path: '/dev/disk/by-id/scsi-35000cca251b3d758-part1'
            devid: 'scsi-35000cca251b3d758-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:9:0'
            whole_disk: 1
            DTL: 45
            create_txg: 4
        children[6]:
            type: 'disk'
            id: 6
            guid: 9408909243862883736
            path: '/dev/disk/by-id/scsi-35000cca251b4ff10-part1'
            devid: 'scsi-35000cca251b4ff10-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:6:0'
            whole_disk: 1
            DTL: 44
            create_txg: 4
        children[7]:
            type: 'disk'
            id: 7
            guid: 7861725104108086664
            path: '/dev/disk/by-id/scsi-35000cca251b628dc-part1'
            devid: 'scsi-35000cca251b628dc-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:4:0'
            whole_disk: 1
            DTL: 43
            create_txg: 4
        children[8]:
            type: 'disk'
            id: 8
            guid: 4321711607497316541
            path: '/dev/disk/by-id/scsi-35000cca251b7fc90-part1'
            devid: 'scsi-35000cca251b7fc90-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:11:0'
            whole_disk: 1
            DTL: 42
            create_txg: 4
        children[9]:
            type: 'disk'
            id: 9
            guid: 15176184833201537495
            path: '/dev/disk/by-id/scsi-35000cca251b7fcb8-part1'
            devid: 'scsi-35000cca251b7fcb8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:1:0'
            whole_disk: 1
            DTL: 41
            create_txg: 4
        children[10]:
            type: 'disk'
            id: 10
            guid: 9932103074347746317
            path: '/dev/disk/by-id/scsi-35000cca251b813f0-part1'
            devid: 'scsi-35000cca251b813f0-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:5:0'
            whole_disk: 1
            DTL: 40
            create_txg: 4
        children[11]:
            type: 'disk'
            id: 11
            guid: 14595263177298823159
            path: '/dev/disk/by-id/scsi-35000cca251b89ad8-part1'
            devid: 'scsi-35000cca251b89ad8-part1'
            phys_path: 'pci-0000:02:00.0-scsi-0:0:2:0'
            whole_disk: 1
            DTL: 39
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
    labels = 2 3

```
