### ISSUE TITLE
Unable to import zpool created under illumos using cache file 

### ISSUE THREAD

**Issue by youzhongyang** [zfsonlinux/zfs#8583]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Oracle Linux
Distribution Version	|  7.6
Linux Kernel	|  4.14.35
Architecture	|  x86_64
ZFS Version	|  0.7.13
SPL Version	|  0.7.13

### Describe the problem you're observing
Unable to import zpool by command 'zpool import -c /etc/zfs/zpool.cache -aN'.

### Describe how to reproduce the problem

I have a zpool created under illumos. Here are what happened:

- Installed zfs 0.7.13 on Oracle Linux 7.6
- zpool import -a, it worked. I saw /etc/zfs/zpool.cache file was created.
- rebooted the host, hoping the zpool would be imported automatically, but it didn't. So I manually ran the import command "zpool import -c /etc/zfs/zpool.cache -aN", I got the following error message:
```
zpool: cannot import 'clusters': one or more devices is currently unavailable
```
- ran 'zpool import -aN', it worked. 

Is this a platform compatibility issue? zdb -C output is pasted. As you can see, there are 'holes', what are they? 

```
# zdb -C
clusters:
    version: 5000
    name: 'clusters'
    state: 0
    txg: 13619887
    pool_guid: 3757410726645497051
    errata: 0
    hostname: 'batfs1399'
    com.delphix:has_per_vdev_zaps
    hole_array[0]: 5
    hole_array[1]: 6
    hole_array[2]: 7
    hole_array[3]: 8
    hole_array[4]: 9
    hole_array[5]: 10
    vdev_children: 11
    vdev_tree:
        type: 'root'
        id: 0
        guid: 3757410726645497051
        children[0]:
            type: 'raidz'
            id: 0
            guid: 5087952512188526339
            nparity: 1
            metaslab_array: 60
            metaslab_shift: 35
            ashift: 12
            asize: 4800745046016
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 35
            children[0]:
                type: 'disk'
                id: 0
                guid: 2192232785760144621
                path: '/dev/nvme2n1p1'
                devid: 'id1,kdev@w75a000df574a1901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@5/pci1344,2d00@0/blkdev@w75A000DF574A1901,0:a'
                whole_disk: 1
                DTL: 3149
                create_txg: 4
                com.delphix:vdev_zap_leaf: 36
            children[1]:
                type: 'disk'
                id: 1
                guid: 10821099920480561631
                path: '/dev/nvme12n1p1'
                devid: 'id1,kdev@w75a0000aac461901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@6/pci1344,2d00@0/blkdev@w75A0000AAC461901,0:a'
                whole_disk: 1
                DTL: 3148
                create_txg: 4
                com.delphix:vdev_zap_leaf: 37
            children[2]:
                type: 'disk'
                id: 2
                guid: 8034097313726034695
                path: '/dev/nvme7n1p1'
                devid: 'id1,kdev@w75a0002b584a1901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@7/pci1344,2d00@0/blkdev@w75A0002B584A1901,0:a'
                whole_disk: 1
                DTL: 3147
                create_txg: 4
                com.delphix:vdev_zap_leaf: 38
        children[1]:
            type: 'raidz'
            id: 1
            guid: 12485452348563225247
            nparity: 1
            metaslab_array: 58
            metaslab_shift: 35
            ashift: 12
            asize: 4800745046016
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 39
            children[0]:
                type: 'disk'
                id: 0
                guid: 16938746747714396375
                path: '/dev/nvme3n1p1'
                devid: 'id1,kdev@w75a00034584a1901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@8/pci1344,2d00@0/blkdev@w75A00034584A1901,0:a'
                whole_disk: 1
                DTL: 3158
                create_txg: 4
                com.delphix:vdev_zap_leaf: 40
            children[1]:
                type: 'disk'
                id: 1
                guid: 8055675365786561295
                path: '/dev/nvme6n1p1'
                devid: 'id1,kdev@w75a000d3ab461901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@9/pci1344,2d00@0/blkdev@w75A000D3AB461901,0:a'
                whole_disk: 1
                DTL: 3157
                create_txg: 4
                com.delphix:vdev_zap_leaf: 41
            children[2]:
                type: 'disk'
                id: 2
                guid: 1340717015081943986
                path: '/dev/nvme4n1p1'
                devid: 'id1,kdev@w75a0003d584a1901/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@a/pci1344,2d00@0/blkdev@w75A0003D584A1901,0:a'
                whole_disk: 1
                DTL: 3156
                create_txg: 4
                com.delphix:vdev_zap_leaf: 42
        children[2]:
            type: 'raidz'
            id: 2
            guid: 531884906567440397
            nparity: 1
            metaslab_array: 57
            metaslab_shift: 35
            ashift: 12
            asize: 4800923566080
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 43
            children[0]:
                type: 'disk'
                id: 0
                guid: 4332955167650098041
                path: '/dev/nvme5n1p1'
                devid: 'id1,kdev@w75a0009f2e451c01/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@b/pci1344,2d00@0/blkdev@w75A0009F2E451C01,0:a'
                whole_disk: 1
                DTL: 3155
                create_txg: 4
                com.delphix:vdev_zap_leaf: 44
            children[1]:
                type: 'disk'
                id: 1
                guid: 1092617531593325661
                path: '/dev/nvme10n1p1'
                devid: 'id1,kdev@w75a000012f451c01/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@c/pci1344,2d00@0/blkdev@w75A000012F451C01,0:a'
                whole_disk: 1
                DTL: 3154
                create_txg: 4
                com.delphix:vdev_zap_leaf: 45
            children[2]:
                type: 'disk'
                id: 2
                guid: 7551452355567154162
                path: '/dev/nvme11n1p1'
                devid: 'id1,kdev@w75a000702d451c01/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@d/pci1344,2d00@0/blkdev@w75A000702D451C01,0:a'
                whole_disk: 1
                DTL: 3153
                create_txg: 4
                com.delphix:vdev_zap_leaf: 46
        children[3]:
            type: 'raidz'
            id: 3
            guid: 16412133368630021221
            nparity: 1
            metaslab_array: 55
            metaslab_shift: 35
            ashift: 12
            asize: 4800923566080
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 47
            children[0]:
                type: 'disk'
                id: 0
                guid: 17702529310176546067
                path: '/dev/nvme8n1p1'
                devid: 'id1,kdev@w75a0001e2f451c01/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@e/pci1344,2d00@0/blkdev@w75A0001E2F451C01,0:a'
                whole_disk: 1
                DTL: 3152
                create_txg: 4
                com.delphix:vdev_zap_leaf: 48
            children[1]:
                type: 'disk'
                id: 1
                guid: 11740209390646083009
                path: '/dev/nvme9n1p1'
                devid: 'id1,kdev@w75a000cc4c451c01/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@f/pci1344,2d00@0/blkdev@w75A000CC4C451C01,0:a'
                whole_disk: 1
                DTL: 3151
                create_txg: 4
                com.delphix:vdev_zap_leaf: 49
            children[2]:
                type: 'disk'
                id: 2
                guid: 312284204476674360
                path: '/dev/nvme13n1p1'
                devid: 'id1,kdev@w75a000f52c451c01/a'
                phys_path: '/pci@9a,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@4/pci1344,2d00@0/blkdev@w75A000F52C451C01,0:a'
                whole_disk: 1
                DTL: 3150
                create_txg: 4
                com.delphix:vdev_zap_leaf: 50
        children[4]:
            type: 'mirror'
            id: 4
            guid: 9855143402539413903
            whole_disk: 0
            metaslab_array: 3136
            metaslab_shift: 31
            ashift: 12
            asize: 375070130176
            is_log: 1
            create_txg: 12596410
            com.delphix:vdev_zap_top: 3135
            children[0]:
                type: 'disk'
                id: 0
                guid: 9418076561442038327
                path: '/dev/nvme0n1p1'
                devid: 'id1,kdev@E8086-INTEL_SSDPE21K375GA_____________________-PHKE7491002X375AGN__-1/a'
                phys_path: '/pci@58,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@4/pci8086,3905@0/blkdev@1,0:a'
                whole_disk: 1
                DTL: 3159
                create_txg: 12596410
                com.delphix:vdev_zap_leaf: 3134
            children[1]:
                type: 'disk'
                id: 1
                guid: 2565775430626578189
                path: '/dev/nvme1n1p1'
                devid: 'id1,kdev@E8086-INTEL_SSDPE21K375GA_____________________-PHKE75100014375AGN__-1/a'
                phys_path: '/pci@9a,0/pci8086,2030@0/pci10b5,9765@0/pci10b5,9765@f/pci8086,3905@0/blkdev@1,0:a'
                whole_disk: 1
                DTL: 3142
                create_txg: 12596410
                com.delphix:vdev_zap_leaf: 3141
        children[5]:
            type: 'hole'
            id: 5
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[6]:
            type: 'hole'
            id: 6
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[7]:
            type: 'hole'
            id: 7
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[8]:
            type: 'hole'
            id: 8
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[9]:
            type: 'hole'
            id: 9
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[10]:
            type: 'hole'
            id: 10
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```

**Comment by ikozhukhov** [comment]
```
zpool get all <pool> | grep feature
```
and show list of features on your Linux and illumos subsystems

**Comment by youzhongyang** [comment]
Under illumos:
```
# zpool get all clusters | grep feature
clusters  feature@async_destroy          enabled                        local
clusters  feature@empty_bpobj            active                         local
clusters  feature@lz4_compress           active                         local
clusters  feature@multi_vdev_crash_dump  enabled                        local
clusters  feature@spacemap_histogram     active                         local
clusters  feature@enabled_txg            active                         local
clusters  feature@hole_birth             active                         local
clusters  feature@extensible_dataset     enabled                        local
clusters  feature@embedded_data          active                         local
clusters  feature@bookmarks              enabled                        local
clusters  feature@filesystem_limits      enabled                        local
clusters  feature@large_blocks           enabled                        local
clusters  feature@sha512                 disabled                       local
clusters  feature@skein                  disabled                       local
clusters  feature@edonr                  disabled                       local
```
Under Linux:
```
# zpool get all clusters | grep feature
clusters  feature@async_destroy          enabled                        local
clusters  feature@empty_bpobj            active                         local
clusters  feature@lz4_compress           active                         local
clusters  feature@multi_vdev_crash_dump  enabled                        local
clusters  feature@spacemap_histogram     active                         local
clusters  feature@enabled_txg            active                         local
clusters  feature@hole_birth             active                         local
clusters  feature@extensible_dataset     enabled                        local
clusters  feature@embedded_data          active                         local
clusters  feature@bookmarks              enabled                        local
clusters  feature@filesystem_limits      enabled                        local
clusters  feature@large_blocks           enabled                        local
clusters  feature@large_dnode            disabled                       local
clusters  feature@sha512                 enabled                        local
clusters  feature@skein                  enabled                        local
clusters  feature@edonr                  enabled                        local
clusters  feature@userobj_accounting     disabled                       local
```
I see no problem.

**Comment by richardelling** [comment]
Since the device paths are very different across OSes, I see no way that the cachefile could be expected to work. Normal import should work.

**Comment by youzhongyang** [comment]
The /etc/zfs/zpool.cache file was created by 'zpool import -a' under Linux, it seems it populates 'path' but keeps the old 'devid' and 'phys_path', is it the reason 'zpool import -c /etc/zfs/zpool.cache' fails? shouldn't the 'devid' and 'phys_path' also be 'refreshed'? I would consider this inconsistency/discrepancy.

**Comment by behlendorf** [comment]
@youzhongyang the `devid` and `phys_path`'s should be updated on `zpool import` as long as you've built ZFS to use `libudev`.  This functionality is enabled by default in all the distribution provided packages I'm aware of.  But if you're rolling you own version make sure `libudev-devel` is installed when configuring and building ZFS.

```
checking libudev.h usability... yes
checking libudev.h presence... yes
checking for libudev.h... yes
checking for library containing udev_device_get_is_initialized... -ludev
```

**Comment by youzhongyang** [comment]
@behlendorf Thanks Brian. Yes I built zfs from source. When I did, it complained about libuuid, libblkid, zlib being required packages, but not libudev. Shouldn't libudev be a required package? what is the reason for it not to be?

Anyway, I will rebuild zfs and report back.

**Comment by behlendorf** [comment]
`libudev` was left as an optional dependency since it's not provided by some distributions.  The platform specific packaging (rpm, deb) requires it as appropriate.

**Comment by youzhongyang** [comment]
I rebuilt zfs, zpool import -a, all the devids and phys_paths in /etc/zfs/zpool.cache are updated; but zpool import -c  /etc/zfs/zpool.cache still failed with the same error:

```
zpool: cannot import 'clusters': one or more devices is currently unavailable
```
Definitely something is not right.

```
# zdb -C
clusters:
    version: 5000
    name: 'clusters'
    state: 0
    txg: 13757867
    pool_guid: 3757410726645497051
    errata: 0
    hostname: 'batfs1399'
    com.delphix:has_per_vdev_zaps
    hole_array[0]: 5
    hole_array[1]: 6
    hole_array[2]: 7
    hole_array[3]: 8
    hole_array[4]: 9
    hole_array[5]: 10
    vdev_children: 11
    vdev_tree:
        type: 'root'
        id: 0
        guid: 3757410726645497051
        children[0]:
            type: 'raidz'
            id: 0
            guid: 5087952512188526339
            nparity: 1
            metaslab_array: 60
            metaslab_shift: 35
            ashift: 12
            asize: 4800745046016
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 35
            children[0]:
                type: 'disk'
                id: 0
                guid: 2192232785760144621
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_1737194A57DF-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_1737194A57DF-part1'
                phys_path: 'pci-0000:61:00.0-nvme-1'
                whole_disk: 1
                DTL: 3149
                create_txg: 4
                com.delphix:vdev_zap_leaf: 36
            children[1]:
                type: 'disk'
                id: 1
                guid: 10821099920480561631
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17391946AC0A-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17391946AC0A-part1'
                phys_path: 'pci-0000:62:00.0-nvme-1'
                whole_disk: 1
                DTL: 3148
                create_txg: 4
                com.delphix:vdev_zap_leaf: 37
            children[2]:
                type: 'disk'
                id: 2
                guid: 8034097313726034695
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_1737194A582B-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_1737194A582B-part1'
                phys_path: 'pci-0000:63:00.0-nvme-1'
                whole_disk: 1
                DTL: 3147
                create_txg: 4
                com.delphix:vdev_zap_leaf: 38
        children[1]:
            type: 'raidz'
            id: 1
            guid: 12485452348563225247
            nparity: 1
            metaslab_array: 58
            metaslab_shift: 35
            ashift: 12
            asize: 4800745046016
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 39
            children[0]:
                type: 'disk'
                id: 0
                guid: 16938746747714396375
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_1737194A5834-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_1737194A5834-part1'
                phys_path: 'pci-0000:64:00.0-nvme-1'
                whole_disk: 1
                DTL: 3158
                create_txg: 4
                com.delphix:vdev_zap_leaf: 40
            children[1]:
                type: 'disk'
                id: 1
                guid: 8055675365786561295
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17391946ABD3-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17391946ABD3-part1'
                phys_path: 'pci-0000:65:00.0-nvme-1'
                whole_disk: 1
                DTL: 3157
                create_txg: 4
                com.delphix:vdev_zap_leaf: 41
            children[2]:
                type: 'disk'
                id: 2
                guid: 1340717015081943986
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_1737194A583D-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_1737194A583D-part1'
                phys_path: 'pci-0000:66:00.0-nvme-1'
                whole_disk: 1
                DTL: 3156
                create_txg: 4
                com.delphix:vdev_zap_leaf: 42
        children[2]:
            type: 'raidz'
            id: 2
            guid: 531884906567440397
            nparity: 1
            metaslab_array: 57
            metaslab_shift: 35
            ashift: 12
            asize: 4800923566080
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 43
            children[0]:
                type: 'disk'
                id: 0
                guid: 4332955167650098041
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C452E9F-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C452E9F-part1'
                phys_path: 'pci-0000:67:00.0-nvme-1'
                whole_disk: 1
                DTL: 3155
                create_txg: 4
                com.delphix:vdev_zap_leaf: 44
            children[1]:
                type: 'disk'
                id: 1
                guid: 1092617531593325661
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C452F01-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C452F01-part1'
                phys_path: 'pci-0000:68:00.0-nvme-1'
                whole_disk: 1
                DTL: 3154
                create_txg: 4
                com.delphix:vdev_zap_leaf: 45
            children[2]:
                type: 'disk'
                id: 2
                guid: 7551452355567154162
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C452D70-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C452D70-part1'
                phys_path: 'pci-0000:69:00.0-nvme-1'
                whole_disk: 1
                DTL: 3153
                create_txg: 4
                com.delphix:vdev_zap_leaf: 46
        children[3]:
            type: 'raidz'
            id: 3
            guid: 16412133368630021221
            nparity: 1
            metaslab_array: 55
            metaslab_shift: 35
            ashift: 12
            asize: 4800923566080
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 47
            children[0]:
                type: 'disk'
                id: 0
                guid: 17702529310176546067
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C452F1E-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C452F1E-part1'
                phys_path: 'pci-0000:6a:00.0-nvme-1'
                whole_disk: 1
                DTL: 3152
                create_txg: 4
                com.delphix:vdev_zap_leaf: 48
            children[1]:
                type: 'disk'
                id: 1
                guid: 11740209390646083009
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C454CCC-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C454CCC-part1'
                phys_path: 'pci-0000:6b:00.0-nvme-1'
                whole_disk: 1
                DTL: 3151
                create_txg: 4
                com.delphix:vdev_zap_leaf: 49
            children[2]:
                type: 'disk'
                id: 2
                guid: 312284204476674360
                path: '/dev/disk/by-id/nvme-Micron_9200_MTFDHAL1T6TCU_17511C452CF5-part1'
                devid: 'nvme-Micron_9200_MTFDHAL1T6TCU_17511C452CF5-part1'
                phys_path: 'pci-0000:b1:00.0-nvme-1'
                whole_disk: 1
                DTL: 3150
                create_txg: 4
                com.delphix:vdev_zap_leaf: 50
        children[4]:
            type: 'mirror'
            id: 4
            guid: 9855143402539413903
            whole_disk: 0
            metaslab_array: 3136
            metaslab_shift: 31
            ashift: 12
            asize: 375070130176
            is_log: 1
            create_txg: 12596410
            com.delphix:vdev_zap_top: 3135
            children[0]:
                type: 'disk'
                id: 0
                guid: 9418076561442038327
                path: '/dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE7491002X375AGN-part1'
                devid: 'nvme-INTEL_SSDPE21K375GA_PHKE7491002X375AGN-part1'
                phys_path: 'pci-0000:60:00.0-nvme-1'
                whole_disk: 1
                DTL: 3159
                create_txg: 12596410
                com.delphix:vdev_zap_leaf: 3134
            children[1]:
                type: 'disk'
                id: 1
                guid: 2565775430626578189
                path: '/dev/disk/by-id/nvme-INTEL_SSDPE21K375GA_PHKE75100014375AGN-part1'
                devid: 'nvme-INTEL_SSDPE21K375GA_PHKE75100014375AGN-part1'
                phys_path: 'pci-0000:bc:00.0-nvme-1'
                whole_disk: 1
                DTL: 3142
                create_txg: 12596410
                com.delphix:vdev_zap_leaf: 3141
        children[5]:
            type: 'hole'
            id: 5
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[6]:
            type: 'hole'
            id: 6
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[7]:
            type: 'hole'
            id: 7
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[8]:
            type: 'hole'
            id: 8
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[9]:
            type: 'hole'
            id: 9
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
        children[10]:
            type: 'hole'
            id: 10
            guid: 0
            metaslab_array: 0
            metaslab_shift: 24
            ashift: 0
            asize: 0
            is_log: 0
            is_hole: 1
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
