### ISSUE TITLE
zdb whole disk:0 ?

### ISSUE THREAD

**Issue by niksfirefly** [zfsonlinux/zfs#8592]
I cleared GPT/MBR before zpool creation with gdisk

I am creating pool on whole NVME disk with command
`zpool create pool /dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-00000_S3W8NX0M215629`

but then zdb shows
whole_disk: 0
why?

```
pool:
    version: 5000
    name: 'pool'
    state: 0
    txg: 4
    pool_guid: 15694434170719111359
    errata: 0
    hostname: 'asgard'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 15694434170719111359
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 1409926228865277844
            path:
'/dev/disk/by-id/nvme-SAMSUNG_MZVLB512HAJQ-00000_S3W8NX0M215629'
            whole_disk: 0
            metaslab_array: 64
            metaslab_shift: 32
            ashift: 9
            asize: 512105381888
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_leaf: 129
            com.delphix:vdev_zap_top: 130
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
