### ISSUE TITLE
zpool import stuck - VERIFY3 PANIC dsl_deadlist_open

### ISSUE THREAD

**Issue by pongraczi** [zfsonlinux/zfs#8612]
### System information

Type | Desktop i5 intel + 4 x 500GB raidz10
 --- | --- 
Distribution Name/Version	| Linuxmint 19.1 (Ubuntu 18.08 bionic)
Linux Kernel	| 4.15.0-47-generic
Architecture	| x86_64
ZFS Version	| 0.7.5-1ubuntu16.4
SPL Version	| 0.7.5-1ubuntu1

### Describe the problem you're observing
**Short version:** after a hardware power issue, mysterious resilvering happened and now it is not possible to **import** the pool:  
```zpool import -F -n  -d /dev/etherd/ -R /mnt/oldroot tank```

```
VERIFY3(0 == dmu_bonus_hold(os, object, dl, &dl->dl_dbuf)) failed (0 == 5) 
PANIC at dsl_deadlist.c:99:dsl_deadlist_open()
```
zdb also crashed, after a short digging (```zdb -AAA -L -dm -p /dev/etherd/ -e tank```):  
```
... lot of input/output error for these datasets:
failed to own dataset 'tank/simplesnap/hn2/quicky/data/vm-2065-disk-7@zfs-auto-snap_hourly-2019-03-11-0317': Input/output error
failed to own dataset 'tank/simplesnap/hn2/quicky/data/vm-2065-disk-7@zfs-auto-snap_hourly-2019-03-09-2217': Input/output error
0 == dmu_bonus_hold(os, object, dl, &dl->dl_dbuf) (0x0 == 0x5)
ASSERT at ../../module/zfs/dsl_deadlist.c:99:dsl_deadlist_open()Interrupted (core created)
```

**Long version:**
The pool looks like this at this momen:  
```
   pool: tank
     id: 16765331400713355408
  state: DEGRADED
 status: One or more devices were being resilvered.
 action: The pool can be imported despite missing or damaged devices.  The
	fault tolerance of the pool may be compromised if imported.
 config:

	tank                      UNAVAIL  missing device
	  mirror-0                DEGRADED
	    e232.2                ONLINE
	    18038925275007282961  UNAVAIL
	  mirror-2                ONLINE
	    e232.1                ONLINE
	    e232.4                ONLINE
```
Chronological order (from older to newest events):
* After a power failure situation, the pool was working fine, except the UNAVAIL disk shown above.
* zfs snapshot issued and created as expected
* after some new power failures, the missing disk appeared
* resilvering started, BUT the 3 disks were resilvering, not the appeared one, so, it seems stupid things started to spread accross the 3 working disks from the 1 
* I was not able to stop the resilvering, it reported 8GB+ resilvered data
* new power outage during resilvering
* system boots up, not possible to import the pool againDataset tank/simplesnap/hn2/quicky/data/vm-2065-disk-7@zfs-auto-snap_hourly-2019-02-25-1317 [ZVOL], ID 643052, cr_txg 43800419, 16.6G, 2 objects
Dataset tank/simplesnap/hn2/quicky/data/vm-2065-disk-7@zfs-auto-snap_hourly-2019-02-
* zpool imports always triggered the VERIFY3/PANIC kernel message and zpool hangs forever, even '-n' specified
* zdb queries usually end with the ASSERT when it started to scan the datasets
I did try to set readonly=on etc., but it is not possible to import.  

In fact, I did not try to drop transactions using these switches (-T nor -X), as I try to keep this messed state and give a chance to access my data again.

So my theory, what happened: after the successfully issues snapshot fixed a consistent state on 3 drives the earlier missing drive (lets name it MESS) appeared. It somehow triggered a resilvering process, but in a wrong way, the source was the MESS and spread something accross the 3 drives, left the pool in this messy state.  

I assume, up to the snapshot transaction the pool should be fine, but the transactions happened after the snapshot created this mess. I assume, if I rollback during the import to the transaction of snapshot, I should got back the pool.

 I can see the snapshots of several datasets in the output of the zdb, so, I know, the cr_txg was 
44366819. I can see this tr number in all snapshots visible in the zdb output. Examples:
```
Dataset tank/src@ipc5 [ZPL], ID 29251, cr_txg 44366819, 3.36G, 374672 objects
Dataset tank/volumes/serial@ipc5 [ZVOL], ID 29540, cr_txg 44366819, 254M, 2 objects
Dataset tank/volumes@ipc5 [ZPL], ID 29536, cr_txg 44366819, 120K, 6 objects
Dataset tank/local/pwrp@ipc5 [ZPL], ID 29544, cr_txg 44366819, 308M, 1052 objects
etc.
```

### Questions
* Does my assumption could be true/valid? (Up to latest snapshot on the pool the data on the disk should be intact and with rollback could be accessible?)
* If the assumption is valid, the correct import formula to check the theory could be (it is for just test the theory, not actually rollback transactions on the pool) :
```zpool import -FX -T 44366819 -n  -o readonly=on -d /dev/etherd/ -R /mnt/oldroot tank```
again, this is for testing and not altering the data on disk, yet
* Do you have any other hints, how to restore the latest snapshot and/or access partially working datasets, if any? (I guess, the answer is no and must use these dangerious switches, -FX -T)

### Attachements
```zdb -AAA -L -Cdm -p /dev/etherd/ -e tank > zdb.log```
[zdb.log](https://github.com/zfsonlinux/zfs/files/3068457/zdb.log)

**Comment by pongraczi** [comment]
Note: there is no difference trying to zpool import or zdb the pool between AtaOverEthernet or locally access.

**Comment by pongraczi** [comment]
Hmmm, the lowest txg number which shows something is 44367153. zdb still ASSERTED and segfaulted, but can find the pool.  
Below that I got zdb: can't open 'tank': No such device or address

```
root@picozfs:~# zdb -AAA -L -Ce -p /dev/disk/by-id -t 44367153 -e tank

MOS Configuration:
        version: 5000
        name: 'tank'
        state: 0
        txg: 44366967
        pool_guid: 16765331400713355408
        errata: 0
        hostname: 'ipc5'
        com.delphix:has_per_vdev_zaps
        hole_array[0]: 1
        vdev_children: 3
        vdev_tree:
            type: 'root'
            id: 0
            guid: 16765331400713355408
            children[0]:
                type: 'mirror'
                id: 0
                guid: 6596804431299031310
                metaslab_array: 31
                metaslab_shift: 32
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 61441
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 18340227539263720614
                    path: '/dev/etherd/e239.8p1'
                    whole_disk: 1
                    DTL: 245855
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61442
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 18038925275007282961
                    path: '/dev/disk/by-id/ata-WDC_WD5000BEVT-00A0RT0_WD-WXN1AB0X5490-part1'
                    whole_disk: 1
                    not_present: 1
                    DTL: 245854
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61443
            children[1]:
                type: 'hole'
                id: 1
                guid: 0
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 0
                ashift: 0
                asize: 0
                is_log: 0
                is_hole: 1
            children[2]:
                type: 'mirror'
                id: 2
                guid: 8874382531035424272
                metaslab_array: 5114
                metaslab_shift: 31
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 5977371
                com.delphix:vdev_zap_top: 61446
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 5573758281844437279
                    path: '/dev/etherd/e239.7p1'
                    whole_disk: 1
                    DTL: 245856
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61447
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 6412630776208911833
                    path: '/dev/etherd/e239.10p1'
                    whole_disk: 1
                    DTL: 4107
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61448
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data
space map refcount mismatch: expected 357 != actual 352
```
```
root@picozfs:~# zdb -AAA -L -Ce -p /dev/disk/by-id -t 44366819 -e tank
zdb: can't open 'tank': No such device or address
root@picozfs:~#
```

Still no positive progress.

**Comment by pongraczi** [comment]
Issued command and results in chronological order:  
* ```zpool import -F -T 44366819 -o readonly=on  -n  -d /dev/disk/by-id/ -R /mnt/tank tank``` - it returned without any output, no hangs, seemed fine
* ```zpool import -F -T 44366819 -o readonly=on    -d /dev/disk/by-id/ -R /mnt/tank tank``` - it returned and reported there is missing device
* rebooting
* ```zpool import -m -o readonly=on    -d /dev/disk/by-id/ -R /mnt/tank tank``` - hangs with the same kernel message: 
```
[  541.206257] VERIFY3(0 == dmu_bonus_hold(os, object, dl, &dl->dl_dbuf)) failed (0 == 5)
[  541.206446] PANIC at dsl_deadlist.c:99:dsl_deadlist_open()
```

**Comment by pongraczi** [comment]
Running zdb to list datasets still crashed and there are several input/output errors (same as before, non important snapshots of datasets):  
```
0 == dmu_bonus_hold(os, object, dl, &dl->dl_dbuf) (0x0 == 0x5)
ASSERT at ../../module/zfs/dsl_deadlist.c:99:dsl_deadlist_open()Félbeszakítva
```
```failed to own dataset 'tank/simplesnap/hn2/quicky/data/vm-2065-disk-7@zfs-auto-snap_hourly-2019-03-09-2217': Input/output error```

Interesting result: the uberblock txg number seems the same as before the the zpool import -T:  
uberblock txg_no:  44367184  
latest snapshot I did: 44366819  

```
root@picozfs:~# zdb -uC  -p /dev/disk/by-id/ -e tank

MOS Configuration:
        version: 5000
        name: 'tank'
        state: 0
        txg: 44366967
        pool_guid: 16765331400713355408
        errata: 0
        hostname: 'ipc5'
        com.delphix:has_per_vdev_zaps
        hole_array[0]: 1
        vdev_children: 3
        vdev_tree:
            type: 'root'
            id: 0
            guid: 16765331400713355408
            children[0]:
                type: 'mirror'
                id: 0
                guid: 6596804431299031310
                metaslab_array: 31
                metaslab_shift: 32
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 61441
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 18340227539263720614
                    path: '/dev/etherd/e239.8p1'
                    whole_disk: 1
                    DTL: 245855
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61442
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 18038925275007282961
                    path: '/dev/disk/by-id/ata-WDC_WD5000BEVT-00A0RT0_WD-WXN1AB0X5490-part1'
                    whole_disk: 1
                    not_present: 1
                    DTL: 245854
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61443
            children[1]:
                type: 'hole'
                id: 1
                guid: 0
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 0
                ashift: 0
                asize: 0
                is_log: 0
                is_hole: 1
            children[2]:
                type: 'mirror'
                id: 2
                guid: 8874382531035424272
                metaslab_array: 5114
                metaslab_shift: 31
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 5977371
                com.delphix:vdev_zap_top: 61446
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 5573758281844437279
                    path: '/dev/etherd/e239.7p1'
                    whole_disk: 1
                    DTL: 245856
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61447
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 6412630776208911833
                    path: '/dev/etherd/e239.10p1'
                    whole_disk: 1
                    DTL: 4107
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61448
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data

Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 44367184
	guid_sum = 6815083940533957213
	timestamp = 1554900142 UTC = Wed Apr 10 14:42:22 2019
	mmp_magic = 00000000a11cea11
	mmp_delay = 0

space map refcount mismatch: expected 357 != actual 352
```

Investigating with different txg number:  
This one failed, even the txg number is the latest successfully issued snapshot:  
```
root@picozfs:~# zdb -uC  -p /dev/disk/by-id/ -t 44366819 -e tank
zdb: can't open 'tank': No such device or address
```
The lowest txg number I got any result, it died on loading spacemap:  
```
root@picozfs:~# zdb -uCb  -e -p /dev/disk/by-id/ -t 44367153 -e tank

MOS Configuration:
        version: 5000
        name: 'tank'
        state: 0
        txg: 44366967
        pool_guid: 16765331400713355408
        errata: 0
        hostname: 'ipc5'
        com.delphix:has_per_vdev_zaps
        hole_array[0]: 1
        vdev_children: 3
        vdev_tree:
            type: 'root'
            id: 0
            guid: 16765331400713355408
            children[0]:
                type: 'mirror'
                id: 0
                guid: 6596804431299031310
                metaslab_array: 31
                metaslab_shift: 32
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 4
                com.delphix:vdev_zap_top: 61441
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 18340227539263720614
                    path: '/dev/etherd/e239.8p1'
                    whole_disk: 1
                    DTL: 245855
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61442
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 18038925275007282961
                    path: '/dev/disk/by-id/ata-WDC_WD5000BEVT-00A0RT0_WD-WXN1AB0X5490-part1'
                    whole_disk: 1
                    not_present: 1
                    DTL: 245854
                    create_txg: 4
                    com.delphix:vdev_zap_leaf: 61443
            children[1]:
                type: 'hole'
                id: 1
                guid: 0
                whole_disk: 0
                metaslab_array: 0
                metaslab_shift: 0
                ashift: 0
                asize: 0
                is_log: 0
                is_hole: 1
            children[2]:
                type: 'mirror'
                id: 2
                guid: 8874382531035424272
                metaslab_array: 5114
                metaslab_shift: 31
                ashift: 12
                asize: 500093681664
                is_log: 0
                create_txg: 5977371
                com.delphix:vdev_zap_top: 61446
                children[0]:
                    type: 'disk'
                    id: 0
                    guid: 5573758281844437279
                    path: '/dev/etherd/e239.7p1'
                    whole_disk: 1
                    DTL: 245856
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61447
                children[1]:
                    type: 'disk'
                    id: 1
                    guid: 6412630776208911833
                    path: '/dev/etherd/e239.10p1'
                    whole_disk: 1
                    DTL: 4107
                    create_txg: 5977371
                    com.delphix:vdev_zap_leaf: 61448
        features_for_read:
            com.delphix:hole_birth
            com.delphix:embedded_data

Uberblock:
	magic = 0000000000bab10c
	version = 5000
	txg = 44367153
	guid_sum = 6815083940533957213
	timestamp = 1554899774 UTC = Wed Apr 10 14:36:14 2019
	mmp_magic = 00000000a11cea11
	mmp_delay = 0


Traversing all blocks to verify nothing leaked ...

loading space map for vdev 0 of 3, metaslab 106 of 116 ...space_map_load(msp->ms_sm, msp->ms_tree, SM_ALLOC) == 0 (0x34 == 0x0)
ASSERT at zdb.c:3238:zdb_leak_init()Félbeszakítva
```
